//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSMutableArray, NSString;

@interface AirKissConfData : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *airkissKey; // @dynamic airkissKey;
@property(retain, nonatomic) NSMutableArray *steps; // @dynamic steps;
@property(retain, nonatomic) NSString *title; // @dynamic title;

@end

