//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AppIconItem : NSObject
{
    NSString *appIconUrl;
    NSString *appID;
    NSString *cmd;
}

@property(retain, nonatomic) NSString *cmd; // @synthesize cmd;
@property(retain, nonatomic) NSString *appID; // @synthesize appID;
@property(retain, nonatomic) NSString *appIconUrl; // @synthesize appIconUrl;
- (void).cxx_destruct;
- (id)init;

@end

