//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class APPortal, NSString;

@protocol APProtalDelegate <NSObject>

@optional
- (void)didFailOfAPPortal:(APPortal *)arg1 errMsg:(NSString *)arg2;
- (void)didSuccessOfAPPortal:(APPortal *)arg1;
- (void)didStartApPortal:(APPortal *)arg1;
- (void)didReadyOfApPortal:(APPortal *)arg1;
@end

