//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CommonMessageCellView.h"

@class AppRecordMessageViewModel, UILabel;

@interface AppRecordMessageCellView : CommonMessageCellView
{
    UILabel *m_titleLabel;
    UILabel *m_descLabel;
}

- (void).cxx_destruct;
- (void)onTouchUpInside;
- (void)onTouchDown;
- (id)operationMenuItems;
- (void)initDescLabel;
- (void)initTitleLabel;
- (void)layoutContentView;

// Remaining properties
@property(readonly, nonatomic) AppRecordMessageViewModel *viewModel; // @dynamic viewModel;

@end

