//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol AVPlayerStateControlDelegate <NSObject>
- (void)ChangeVideoDownloadMode:(unsigned long long)arg1;
- (void)OnUpdateThumbImage:(NSString *)arg1;
- (void)videoDownloadErrorExpired:(_Bool)arg1;
- (void)startToPlayVideo;
- (void)updateVideoTotalTime:(double)arg1;
- (void)showVideoLoadingView;
- (void)hideVideoLoadingView;
- (void)playerOnDownloaded;
- (void)pauseForDownloading:(_Bool)arg1;
@end

