//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface BackupStartGeneralInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned long long deviceFreeSpace; // @dynamic deviceFreeSpace;
@property(retain, nonatomic) NSString *deviceId; // @dynamic deviceId;
@property(retain, nonatomic) NSString *deviceName; // @dynamic deviceName;
@property(retain, nonatomic) NSString *model; // @dynamic model;
@property(retain, nonatomic) NSString *systemName; // @dynamic systemName;
@property(retain, nonatomic) NSString *systemVersion; // @dynamic systemVersion;
@property(nonatomic) unsigned int wechatVersion; // @dynamic wechatVersion;

@end

