//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class BaseRequest, NSString;

@interface BizScanProductReportReq : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) BaseRequest *baseRequest; // @dynamic baseRequest;
@property(nonatomic) unsigned int count; // @dynamic count;
@property(retain, nonatomic) NSString *deviceBrand; // @dynamic deviceBrand;
@property(retain, nonatomic) NSString *deviceModel; // @dynamic deviceModel;
@property(retain, nonatomic) NSString *languageVer; // @dynamic languageVer;
@property(retain, nonatomic) NSString *logExt; // @dynamic logExt;
@property(nonatomic) unsigned int logId; // @dynamic logId;
@property(retain, nonatomic) NSString *osName; // @dynamic osName;
@property(retain, nonatomic) NSString *osVersion; // @dynamic osVersion;
@property(retain, nonatomic) NSString *productid; // @dynamic productid;
@property(nonatomic) unsigned int showtype; // @dynamic showtype;
@property(retain, nonatomic) NSString *statid; // @dynamic statid;
@property(nonatomic) unsigned int type; // @dynamic type;
@property(retain, nonatomic) NSString *value; // @dynamic value;

@end

