//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMSearchBarDisplayController.h"

#import "ContactsDataLogicDelegate.h"
#import "IContactMgrExt.h"
#import "IWCDeviceBrandMgrExt.h"
#import "MMSearchBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WCActionSheetDelegate.h"

@class BrandServiceHeadImageProvider, ContactsDataLogic, MMLoadingView, MMSearchBar, MMTableView, NSIndexPath, NSMutableArray, NSMutableDictionary, NSString;

@interface BrandContactsViewController : MMSearchBarDisplayController <UITableViewDelegate, UITableViewDataSource, ContactsDataLogicDelegate, MMSearchBarDelegate, IContactMgrExt, WCActionSheetDelegate, IWCDeviceBrandMgrExt>
{
    MMTableView *_tableView;
    MMSearchBar *_searchBar;
    BrandServiceHeadImageProvider *_headImageCache;
    ContactsDataLogic *_contactsDataLogic;
    NSMutableArray *_sectionKeyArray;
    NSMutableDictionary *_allContactsDic;
    NSMutableDictionary *_oldSubscribeStatusDict;
    unsigned int _searchScene;
    MMLoadingView *_loadingView;
    NSIndexPath *_unfocusIndexPath;
}

@property(retain, nonatomic) NSIndexPath *unfocusIndexPath; // @synthesize unfocusIndexPath=_unfocusIndexPath;
@property(retain, nonatomic) MMLoadingView *loadingView; // @synthesize loadingView=_loadingView;
@property(nonatomic) unsigned int searchScene; // @synthesize searchScene=_searchScene;
- (void).cxx_destruct;
- (void)stopLoadingWithFailText:(id)arg1;
- (void)stopLoadingWithOKText:(id)arg1;
- (void)startLoadingWithText:(id)arg1;
- (void)onWCDeviceUnbindEnd:(id)arg1 Error:(id)arg2;
- (void)cancelFocus;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)cancelFoucsAtIndex:(id)arg1;
- (id)contactAtIndex:(id)arg1;
- (void)onDeleteContact:(id)arg1;
- (void)onModifyContact:(id)arg1;
- (void)displayControllerSetActive:(_Bool)arg1 animated:(_Bool)arg2;
- (_Bool)hidesBottomBarWhenPushed;
- (_Bool)shouldShowTabbarAfterSearchBarBecomeUnActive;
- (void)SearchBarBecomeUnActive;
- (void)SearchBarBecomeActive;
- (void)OnVoiceSearchButtonDown;
- (void)resetTableViewOffset:(id)arg1;
- (void)doSearch:(id)arg1 Pre:(_Bool)arg2;
- (void)didSearchViewTableSelect:(id)arg1;
- (void)delayFinishSearch;
- (double)heightForSearchViewTable:(id)arg1;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)cellForSearchViewTable:(id)arg1 index:(id)arg2;
- (void)delaySearch:(id)arg1 slowMode:(_Bool)arg2;
- (void)delaySearchImp:(id)arg1;
- (void)cancelSearch;
- (void)doSearch:(id)arg1;
- (_Bool)onFilterContactCandidate:(id)arg1;
- (void)onContactsDataChange;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)openContactInfoView:(int)arg1;
- (void)onShowSearchBrandView:(id)arg1;
- (void)makeCell:(id)arg1 ForSearchContact:(id)arg2;
- (void)makeCell:(id)arg1 section:(unsigned long long)arg2 row:(unsigned long long)arg3;
- (void)initSearchBar;
- (void)viewDidLayoutSubviews;
- (void)initLoadingView;
- (void)initTableView;
- (void)initView;
- (void)sort;
- (void)initData;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)willAppear;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

