//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCDBCoding.h"

@class NSString;

@interface CEmoticonPackageWrap : NSObject <WCDBCoding>
{
    NSString *m_packageId;
    NSString *m_packageName;
    unsigned int m_payStatus;
    unsigned int m_downloadStatus;
    unsigned int m_installTime;
    unsigned int m_removeTime;
    NSString *m_iconUrl;
    NSString *m_panelUrl;
    unsigned int ConIntRes1;
    unsigned int ConIntRes2;
    unsigned int ConIntRes3;
    NSString *ConStrRes1;
    NSString *ConStrRes2;
    NSString *ConStrRes3;
    long long m___rowID;
}

+ (id)packageItemFromSummary:(id)arg1;
+ (const basic_string_a490aa4c *)getWCDBPrimaryColumnName;
+ (const struct WCDBIndexHelper *)getWCDBIndexArray;
+ (unsigned long long)getWCDBIndexArrayCount;
+ (const map_0e718273 *)getFileValueTagIndexMap;
+ (id)getFileValueTypeTable;
+ (const map_0e718273 *)getPackedValueTagIndexMap;
+ (id)getPackedValueTypeTable;
+ (const map_7a576766 *)getValueNameIndexMap;
+ (id)getValueTable;
+ (id)dummyObject;
@property(nonatomic) long long __rowID; // @synthesize __rowID=m___rowID;
@property(retain, nonatomic) NSString *ConStrRes3; // @synthesize ConStrRes3;
@property(retain, nonatomic) NSString *ConStrRes2; // @synthesize ConStrRes2;
@property(retain, nonatomic) NSString *ConStrRes1; // @synthesize ConStrRes1;
@property(nonatomic) unsigned int ConIntRes3; // @synthesize ConIntRes3;
@property(nonatomic) unsigned int ConIntRes2; // @synthesize ConIntRes2;
@property(nonatomic) unsigned int ConIntRes1; // @synthesize ConIntRes1;
@property(nonatomic) unsigned int m_removeTime; // @synthesize m_removeTime;
@property(nonatomic) unsigned int m_installTime; // @synthesize m_installTime;
@property(nonatomic) unsigned int m_downloadStatus; // @synthesize m_downloadStatus;
@property(nonatomic) unsigned int m_payStatus; // @synthesize m_payStatus;
@property(retain, nonatomic) NSString *m_panelUrl; // @synthesize m_panelUrl;
@property(retain, nonatomic) NSString *m_iconUrl; // @synthesize m_iconUrl;
@property(retain, nonatomic) NSString *m_packageName; // @synthesize m_packageName;
@property(retain, nonatomic) NSString *m_packageId; // @synthesize m_packageId;
- (void).cxx_destruct;
- (id)init;
@property(readonly, copy) NSString *description;
- (_Bool)isTusiji;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (const WCDBCondition_22fabacd *)db_ConStrRes3;
- (const WCDBCondition_22fabacd *)db_ConStrRes2;
- (const WCDBCondition_22fabacd *)db_ConStrRes1;
- (const WCDBCondition_c6db074e *)db_ConIntRes3;
- (const WCDBCondition_c6db074e *)db_ConIntRes2;
- (const WCDBCondition_c6db074e *)db_ConIntRes1;
- (const WCDBCondition_c6db074e *)db_m_removeTime;
- (const WCDBCondition_c6db074e *)db_m_installTime;
- (const WCDBCondition_c6db074e *)db_m_downloadStatus;
- (const WCDBCondition_c6db074e *)db_m_payStatus;
- (const WCDBCondition_22fabacd *)db_m_panelUrl;
- (const WCDBCondition_22fabacd *)db_m_iconUrl;
- (const WCDBCondition_22fabacd *)db_m_packageName;
- (const WCDBCondition_22fabacd *)db_m_packageId;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

