//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CGroupOpLog : NSObject
{
}

- (_Bool)add_QuitGroup:(id)arg1 withUsrName:(id)arg2 NeedSync:(_Bool)arg3;
- (_Bool)add_MemberSwitch:(id)arg1 usrName:(id)arg2 flag:(unsigned int)arg3 open:(_Bool)arg4 sync:(_Bool)arg5;
- (_Bool)add_SetGroupTopic:(id)arg1 withTopic:(id)arg2 NeedSync:(_Bool)arg3;
- (id)init;

@end

