//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CMMVector : NSObject
{
    struct vector<__unsafe_unretained id, std::__1::allocator<__unsafe_unretained id>> m_vecObject;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)dealloc;
- (id)at:(unsigned int)arg1;
- (unsigned int)count;
- (void)removeAllObjects;
- (_Bool)containsObject:(id)arg1;
- (_Bool)removeObject:(id)arg1;
- (void)addObject:(id)arg1;
- (id)init;

@end

