//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CNewSyncWrap : NSObject
{
    unsigned int m_uiSelector;
    unsigned int m_uiCgi;
    _Bool m_bIsSyncIng;
    _Bool m_bContinue;
    NSString *m_nsSyncKeyMd5;
    unsigned int m_uiSyncBufferType;
}

@property(nonatomic) unsigned int m_uiSyncBufferType; // @synthesize m_uiSyncBufferType;
@property(retain, nonatomic) NSString *m_nsSyncKeyMd5; // @synthesize m_nsSyncKeyMd5;
@property(nonatomic) _Bool m_bContinue; // @synthesize m_bContinue;
@property(nonatomic) _Bool m_bIsSyncIng; // @synthesize m_bIsSyncIng;
@property(nonatomic) unsigned int m_uiCgi; // @synthesize m_uiCgi;
@property(nonatomic) unsigned int m_uiSelector; // @synthesize m_uiSelector;
- (void).cxx_destruct;
- (id)init;

@end

