//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface COOBData : NSObject
{
    unsigned int m_uiType;
    unsigned int m_uiTime;
    NSString *m_nsIPPort;
}

@property(retain, nonatomic) NSString *m_nsIPPort; // @synthesize m_nsIPPort;
@property(nonatomic) unsigned int m_uiTime; // @synthesize m_uiTime;
@property(nonatomic) unsigned int m_uiType; // @synthesize m_uiType;
- (void).cxx_destruct;
- (void)LoadDataFromOOBData:(id)arg1;
- (id)init;

@end

