//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CPKeyIncreaseInfo : NSObject
{
    NSString *_cpKey;
    unsigned long long _threadId;
}

@property(nonatomic) unsigned long long threadId; // @synthesize threadId=_threadId;
@property(retain, nonatomic) NSString *cpKey; // @synthesize cpKey=_cpKey;
- (void).cxx_destruct;

@end

