//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseVoicePrintViewController.h"

@class UIActivityIndicatorView, UIButton, UIImageView, UILabel, UIView;

@interface CreateVoicePrintViewController : BaseVoicePrintViewController
{
    UIButton *_next_button;
    UIButton *_done_button;
    UILabel *_step_Label;
    UIImageView *_doneImageView;
    UIView *_holdTalkTipView;
    UIView *_enviromentCheckView;
    UIButton *_envReCheckBtn;
    UIButton *_envCancelBtn;
    UILabel *_enviromentCheckLabel;
    UIImageView *_enviromentDoneImageView;
    UIActivityIndicatorView *_environmentCheckIndicator;
    _Bool isFirstDoGuideTextAnimation;
}

- (void).cxx_destruct;
- (void)OnEnvironmentReCheckButton:(id)arg1;
- (void)onTryVerifyBtn:(id)arg1;
- (void)onTalkButtonCancel:(id)arg1;
- (void)OnTalkButtonPress:(id)arg1;
- (void)backButtonDone:(id)arg1;
- (void)startDoGuideTextAnimation;
- (void)ShowStepView;
- (void)SetIsFirstStep:(_Bool)arg1;
- (void)ShowCreateErrorAndMustEscScene;
- (void)ShowCreateDoneScene;
- (void)ShowSecondGuideScene;
- (void)ShowRecordScene;
- (void)ShowEnvironmentCheckScene:(_Bool)arg1;
- (void)ShowFirstGuideScene;
- (void)ShowRedoScene;
- (void)makeCheckEnvironmentView;
- (void)makeNextButton;
- (void)stopGetResource;
- (void)startGetResource;
- (void)OnNextButtonPress:(id)arg1;
- (void)viewDidLoad;
- (void)initStepLabel;
- (void)initHoldTipView;
- (void)initBaseView;
- (void)dealloc;
- (id)init;

@end

