//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface DeviceRankUserProfile : MMObject
{
    NSString *nsUsername;
    NSString *nsCoverUrl;
}

+ (void)initialize;
@property(retain, nonatomic) NSString *nsCoverUrl; // @synthesize nsCoverUrl;
@property(retain, nonatomic) NSString *nsUsername; // @synthesize nsUsername;
- (void).cxx_destruct;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;

@end

