//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface EditImageReport : NSObject
{
}

+ (void)EditImageReportOverallSendingEditedImage:(unsigned int)arg1 withAllImage:(unsigned int)arg2 fromScene:(unsigned int)arg3;
+ (void)EditImageReportSingleSendBehavior:(id)arg1 isOriginal:(unsigned int)arg2 fromScene:(unsigned int)arg3;
+ (void)EditImageReportClickBehavior:(unsigned int)arg1 fromScene:(unsigned int)arg2;

@end

