//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class ColorGradientBar, NSMutableArray, UIButton, UIColor, UIView;

@interface EditImagePenToolAttrView : MMUIView
{
    ColorGradientBar *colorBar;
    UIView *colorDot;
    NSMutableArray *_colorArr;
    NSMutableArray *_dotArr;
    int _selectedNumber;
    UIView *_line;
    UIButton *_undoBtn;
    UIView *_vline;
    _Bool _enable;
    UIColor *_selectedColor;
    id <EditImagePenToolAttrDelegate> _m_delegate;
}

@property(nonatomic) __weak id <EditImagePenToolAttrDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
@property(retain, nonatomic) UIColor *_selectedColor; // @synthesize _selectedColor;
- (void).cxx_destruct;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)handleTouches:(id)arg1 withEvent:(id)arg2;
- (double)getLineWidth;
- (id)getLineColor;
- (void)setSelectedDotBorder:(unsigned int)arg1;
- (void)setSelectedColorNumber:(unsigned int)arg1;
- (void)setUndoEnable:(_Bool)arg1;
- (void)onUndoEditImage;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

