//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "IUiUtilExt.h"
#import "UITextViewDelegate.h"
#import "textViewDelegate.h"

@class MMTextView, NSString, UIButton, UIView;

@interface EditImageTextInputView : MMUIView <textViewDelegate, UITextViewDelegate, IUiUtilExt>
{
    MMTextView *_inputView;
    UIButton *_confirmBtn;
    UIButton *_cancelBtn;
    id <EditImageTextInputDelegate> _delegate;
    NSString *_textStr;
    UIView *_textView;
}

@property(retain, nonatomic) UIView *_textView; // @synthesize _textView;
@property(copy, nonatomic) NSString *_textStr; // @synthesize _textStr;
@property(nonatomic) __weak id <EditImageTextInputDelegate> _delegate; // @synthesize _delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)onMainWindowFrameChanged;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)onConfirm;
- (void)onCancel;
- (void)dropDownAndRemove;
- (void)didMoveToSuperview;
- (id)initWithDelegate:(id)arg1 withDefaultText:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

