//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "EditImageUIView.h"

@class NSMutableArray, UIImage, UIImageView;

@interface EditImageMosaicBrushView : EditImageUIView
{
    UIImage *_img;
    UIImageView *_imageView;
    unsigned long long _style;
    double _lineWidth;
    _Bool _initial;
    double _minDis;
    NSMutableArray *_pointArray;
    UIImage *_cacheImg;
}

- (void).cxx_destruct;
- (void)updateCachedImage;
- (void)draw;
- (void)drawMosaicAtPoint:(struct CGPoint)arg1 withColor:(id)arg2 withRotation:(double)arg3;
- (id)initWithFrame:(struct CGRect)arg1 withToolType:(int)arg2 withBrushStyle:(unsigned long long)arg3 LineWidth:(double)arg4;
- (id)initWithBrushStyle:(unsigned long long)arg1 LineWidth:(double)arg2 withColor:(id)arg3 withCenter:(struct CGPoint)arg4;
- (id)initWithLineWidth:(double)arg1 withColor:(id)arg2 withCenter:(struct CGPoint)arg3;

@end

