//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface EmoticonStoreReportInfo : NSObject
{
    unsigned long long _searchId;
    unsigned long long _docId;
}

@property(nonatomic) unsigned long long docId; // @synthesize docId=_docId;
@property(nonatomic) unsigned long long searchId; // @synthesize searchId=_searchId;

@end

