//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CommonMessageViewModel.h"

#import "IEmoticonDownloadExt.h"

@interface EmoticonMessageViewModel : CommonMessageViewModel <IEmoticonDownloadExt>
{
    unsigned long long _msgDownloadStatus;
    struct CGSize _noImageSize;
}

+ (_Bool)canCreateMessageViewModelWithMessageWrap:(id)arg1;
@property(nonatomic) unsigned long long msgDownloadStatus; // @synthesize msgDownloadStatus=_msgDownloadStatus;
@property(nonatomic) struct CGSize noImageSize; // @synthesize noImageSize=_noImageSize;
- (void)OnEmoticonDownload:(unsigned int)arg1 withMsgWrap:(id)arg2;
@property(readonly, nonatomic) _Bool isShowRewardTipsView;
- (struct CGSize)measureContentViewSize:(struct CGSize)arg1;
- (id)initWithMessageWrap:(id)arg1 contact:(id)arg2 chatContact:(id)arg3;
- (void)dealloc;
- (id)cellViewClassName;

@end

