//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class FavoritesTagDB;

@interface FavoritesTagMgr : MMObject
{
    FavoritesTagDB *_favTagDB;
}

- (void).cxx_destruct;
- (id)getItemTags:(unsigned int)arg1;
- (id)getAllTags;
- (void)updateItemTags:(id)arg1 byFavLocalId:(unsigned int)arg2;
- (void)deleteItemTagsByFavLocalId:(unsigned int)arg1;
- (void)initDB:(id)arg1;
- (id)init;

@end

