//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

#import "MFBanner.h"

@class FavBannerTipBkgView, UIImageView, UILabel;

@interface FavWarningBannerView : UIButton <MFBanner>
{
    UILabel *m_textLabel;
    UIImageView *m_arrowImageView;
    FavBannerTipBkgView *m_bkgView;
    int bannerType;
    id <FavWarningBannerViewDelegate> delegate;
}

@property(nonatomic) int bannerType; // @synthesize bannerType;
@property(nonatomic) __weak id <FavWarningBannerViewDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)relayoutViews;
- (void)initArrowImage;
- (void)initText;
- (void)initUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

