//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FileQueue : NSObject
{
    NSString *m_nsFilePath;
    int m_codingMethod;
    Class m_elementClass;
}

- (void).cxx_destruct;
- (_Bool)clear;
- (id)getAll;
- (_Bool)pop;
- (id)getTop;
- (_Bool)modifyTop:(id)arg1;
- (_Bool)push:(id)arg1;
- (_Bool)syncToFile;
- (void)setUnArchiveResult:(id)arg1;
- (id)getArchiveTarget;
- (void)dealloc;
- (id)initWithNSCodingFilePath:(id)arg1;

@end

