//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMTableViewCell.h"

@class MMUILabel, UIImageView;

@interface FTSCreateChatRoomCell : MMTableViewCell
{
    UIImageView *_imageView;
    MMUILabel *_intentLabel;
    MMUILabel *_descLabel;
}

- (void).cxx_destruct;
- (void)updateCellWithKeywords:(id)arg1;
- (void)initView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

