//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMTableViewCell.h"

@class AttributeLabel, CContact, MMBrandHeadImageView, MMHeadImageView, MMUILabel, NSArray, NSString, SearchMatchTip, UIButton;

@interface FTSContactCell : MMTableViewCell
{
    CContact *_contact;
    NSString *_searchText;
    SearchMatchTip *_matchTip;
    NSArray *_arrKeyword;
    id <FTSContactCellDelegate> _delegate;
    MMBrandHeadImageView *_brandHeadImageView;
    MMHeadImageView *_headImageView;
    AttributeLabel *_displayNameLabel;
    AttributeLabel *_detailLabel;
    UIButton *_chatButton;
    MMUILabel *_appTypeLabel;
}

@property(retain, nonatomic) NSString *searchText; // @synthesize searchText=_searchText;
@property(nonatomic) __weak id <FTSContactCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateContact:(id)arg1 searchText:(id)arg2 matchTip:(id)arg3 keywords:(id)arg4;
- (void)updateStatus:(_Bool)arg1;
- (void)dealloc;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)initView;
- (void)onChatButtonClicked;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

