//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FTSFavUtil : NSObject
{
}

+ (id)getLastFavItem;
+ (id)getChatRoomDisplayName:(id)arg1;
+ (id)getNormalContactDisplayName:(id)arg1;
+ (id)GetFavItemSourceSearchString:(id)arg1;
+ (id)GetRecordDataSearchString:(id)arg1;
+ (id)ConvertFavItem2FTSFavSearchItem:(id)arg1;
+ (id)getFavSearchItemsByLocalIds:(id)arg1;
+ (id)getFavSearchItemsFrom:(unsigned int)arg1 limit:(unsigned int)arg2;

@end

