//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IFTSContactDataProviderExt.h"

@class NSMutableArray, NSMutableDictionary;

@interface FTSMultiContactSearchLogic : NSObject <IFTSContactDataProviderExt>
{
    NSMutableArray *_arrContact;
    NSMutableDictionary *_dicContact;
    NSMutableArray *_arrKeywords;
    NSMutableArray *_arrResultWrap;
    _Bool _hasStaredSearch;
    id <FTSMultiContactSearchDelegate> _delegate;
}

+ (id)FilterArrKeywords:(id)arg1;
@property(nonatomic) __weak id <FTSMultiContactSearchDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onContactReload;
- (void)sortContacts:(id)arg1 matchTips:(id)arg2;
- (void)asyncSearch;
- (void)appendResultWrap:(id)arg1;
- (id)getArrResultWrap;
- (_Bool)isTargetContact:(id)arg1;
- (void)fillSourceContact;
- (void)initData:(id)arg1;
- (void)dealloc;
- (id)initWithKeywords:(id)arg1;

@end

