//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GameCenterSearchBaseCell.h"

@interface GameCenterSearchRecommendCell : GameCenterSearchBaseCell
{
}

+ (void)loadSubviews:(id)arg1 recommendItem:(id)arg2;
+ (double)calCellHeight:(id)arg1;

@end

