//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GameCenterEntranceInfo : NSObject
{
    int _entranceNotifyType;
    NSString *_iconUrl;
    NSString *_desc;
}

@property(nonatomic) int entranceNotifyType; // @synthesize entranceNotifyType=_entranceNotifyType;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
- (void).cxx_destruct;

@end

