//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GameCenterIndexTopBanner : NSObject
{
    unsigned int _topBannerId;
    unsigned long long _topBannerState;
    NSString *_bigPicUrl;
    NSString *_bigPicJumpUrl;
    NSString *_smallPicUrl;
    NSString *_classifyBtnIconUrl;
}

@property(retain, nonatomic) NSString *classifyBtnIconUrl; // @synthesize classifyBtnIconUrl=_classifyBtnIconUrl;
@property(nonatomic) unsigned int topBannerId; // @synthesize topBannerId=_topBannerId;
@property(retain, nonatomic) NSString *smallPicUrl; // @synthesize smallPicUrl=_smallPicUrl;
@property(retain, nonatomic) NSString *bigPicJumpUrl; // @synthesize bigPicJumpUrl=_bigPicJumpUrl;
@property(retain, nonatomic) NSString *bigPicUrl; // @synthesize bigPicUrl=_bigPicUrl;
@property(nonatomic) unsigned long long topBannerState; // @synthesize topBannerState=_topBannerState;
- (void).cxx_destruct;

@end

