//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@interface HeadRtcp : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) long long i64QoSver; // @dynamic i64QoSver;
@property(nonatomic) unsigned int u16LocalEngineVer; // @dynamic u16LocalEngineVer;
@property(nonatomic) unsigned int u16RemoteEngineVer; // @dynamic u16RemoteEngineVer;
@property(nonatomic) unsigned int u16Seq; // @dynamic u16Seq;
@property(nonatomic) unsigned int u32QoSip; // @dynamic u32QoSip;
@property(nonatomic) unsigned int u8LocalNetType; // @dynamic u8LocalNetType;
@property(nonatomic) unsigned int u8RemoteNetType; // @dynamic u8RemoteNetType;
@property(nonatomic) unsigned int u8Type; // @dynamic u8Type;
@property(nonatomic) unsigned int u8Version; // @dynamic u8Version;

@end

