//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSData;

@interface HWParamBuffer : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int headerLen; // @dynamic headerLen;
@property(retain, nonatomic) NSData *ppsbuf; // @dynamic ppsbuf;
@property(retain, nonatomic) NSData *spsbuf; // @dynamic spsbuf;

@end

