//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ImageEffect : NSObject
{
}

+ (id)convolveImage:(id)arg1 withBlurRadius:(int)arg2;
+ (char *)bitmapFromImage:(id)arg1;
+ (id)imageWithBits:(char *)arg1 withSize:(struct CGSize)arg2;
+ (id)blurView:(id)arg1;

@end

