//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "CAAnimationDelegate.h"

@class NSString, UIImageView;

@interface IntroView : MMUIView <CAAnimationDelegate>
{
    NSString *_title;
    NSString *_content;
    UIImageView *_backgroundView;
    id <WCIntroViewDelegate> _mydelegate;
}

@property(nonatomic) __weak id <WCIntroViewDelegate> _mydelegate; // @synthesize _mydelegate;
@property(retain, nonatomic) NSString *_content; // @synthesize _content;
@property(retain, nonatomic) NSString *_title; // @synthesize _title;
- (void).cxx_destruct;
- (void)hideCloseBtn;
- (void)onCloseIntroView;
- (void)onTipsBtnPressed:(id)arg1;
- (void)onIKnowItBtnClick:(id)arg1;
- (void)showAnimation;
- (void)initViewWithoutTitle;
- (void)initView;
- (id)initWithFrame:(struct CGRect)arg1 andTittle:(id)arg2 andContent:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

