//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class OCRResult;

@protocol IOCRTransMgrExt <NSObject>

@optional
- (void)OnSendOCRImage:(OCRResult *)arg1 Err:(int)arg2;
@end

