//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, ShakeCardData;

@protocol IShakeCardMgrExt <NSObject>

@optional
- (void)onShakeCardEntranceChange;
- (void)onShakeCardRedDotChange;
- (void)onShakeCardResp:(ShakeCardData *)arg1 errorType:(unsigned long long)arg2 errorMsg:(NSString *)arg3;
@end

