//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JSApiScopeConfirmWindow, NSArray;

@protocol JSApiScopeConfirmWindowDelegate <NSObject>
- (void)onScopeWindowCancel:(JSApiScopeConfirmWindow *)arg1;
- (void)onScopeWindowConfirm:(JSApiScopeConfirmWindow *)arg1 withScope:(NSArray *)arg2;
@end

