//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseReq.h"

@class NSString, WXMediaMessage;

@interface LaunchFromWXReq : BaseReq
{
    NSString *lang;
    NSString *country;
    WXMediaMessage *message;
}

@property(retain, nonatomic) WXMediaMessage *message; // @synthesize message;
@property(retain, nonatomic) NSString *country; // @synthesize country;
@property(retain, nonatomic) NSString *lang; // @synthesize lang;
- (void).cxx_destruct;
- (id)init;

@end

