//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSNumber, NSString;

@protocol MCssParserDelegate <NSObject>
- (void)onCssParseEnd;
- (void)onCssParseStart;
- (NSString *)onNextCssFile;
- (void)onParseErrorInFile:(NSString *)arg1 onLineNumber:(NSNumber *)arg2 withText:(NSString *)arg3 withErrorMessage:(NSString *)arg4;
- (void)onScriptFunctionWithSelectors:(NSArray *)arg1 withStatements:(NSArray *)arg2;
- (void)onReceiveCssRulesetWithSelectors:(NSArray *)arg1 withDeclarations:(NSDictionary *)arg2;
@end

