//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MessageNodeComponentHelper : NSObject
{
}

+ (id)getSourceViewWithTitle:(id)arg1 iconName:(id)arg2 maxWidth:(double)arg3;
+ (id)getSourceViewWithTitle:(id)arg1 iconImage:(id)arg2 maxWidth:(double)arg3 withBkgImg:(_Bool)arg4 withTailTag:(id)arg5;

@end

