//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "MFMassSendBarDelegate.h"
#import "MassSendShortVideoExt.h"

@class NSMutableArray, NSString;

@interface MFMassSendBannerLogic : MMObject <MassSendShortVideoExt, MFMassSendBarDelegate>
{
    NSMutableArray *m_bannerAry;
    id <MFMassSendBannerDelegate> _delegate;
}

@property(nonatomic) __weak id <MFMassSendBannerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onMassSendBarProgressAnimEnd:(id)arg1;
- (void)onMassSendBarCancel:(id)arg1;
- (void)onMassSendBarClick:(id)arg1;
- (id)findMassSendBar:(id)arg1;
- (void)MassSendShortVideoProgress:(id)arg1 finishedLen:(int)arg2 totalLen:(int)arg3;
- (void)MassSendShortVideoOK:(id)arg1;
- (void)MassSendShortVideoFail:(id)arg1;
- (void)MassSendShortVideoCancel:(id)arg1;
- (void)MassSendShortVideoStart:(id)arg1;
- (void)excuteBlockInMainQueue:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

