//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MMAlbumDataProviderForALAssetLibrary : NSObject
{
}

+ (void)FetchLastMMAssetWith:(CDUnknownBlockType)arg1 inSecond:(double)arg2;
+ (void)FirstMMAlbumWith:(CDUnknownBlockType)arg1 errorBlock:(CDUnknownBlockType)arg2 shouldIncludeVideo:(_Bool)arg3 isOnlyShowVideo:(_Bool)arg4;
+ (void)FetchMMAlbumWithID:(id)arg1 With:(CDUnknownBlockType)arg2 errorBlock:(CDUnknownBlockType)arg3 shouldIncludeVideo:(_Bool)arg4 isOnlyShowVideo:(_Bool)arg5;
+ (void)albumForALAssetLibraryIncludingAllVideosWithMaxVideoDuration:(double)arg1 minVideoDuration:(double)arg2 ascending:(_Bool)arg3 completionHandler:(CDUnknownBlockType)arg4;
+ (void)albumForALAssetLibraryIncludingAllVideosWithMaxVideoDuration:(double)arg1 minVideoDuration:(double)arg2 completionHandler:(CDUnknownBlockType)arg3;
+ (void)AllMMAlbumsForAssetLibrbaryWith:(CDUnknownBlockType)arg1 errorBlock:(CDUnknownBlockType)arg2 shouldIncludeVideo:(_Bool)arg3 isOnlyShowVideo:(_Bool)arg4;

@end

