//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMAlbum.h"

@interface MMAlbumForiOS8Plus : MMAlbum
{
}

- (void)updateFetchResult:(id)arg1;
- (id)getFetchResult;

@end

