//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, UIImage;

@protocol MMAssetBigImageDelegate <NSObject>
- (void)onGetBigImageError;
- (void)onGetBigImage:(UIImage *)arg1 data:(NSData *)arg2;
@end

