//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MMCharacterSet : NSObject
{
}

+ (long long)detectWritingDirection:(id)arg1;
+ (id)getHebrewUnicodeCharSet;
+ (id)getArabicUnicodeCharSet;

@end

