//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@interface MMDBMigrationUtil : MMObject
{
}

+ (void)setFlagFinished:(unsigned long long)arg1;
+ (_Bool)isFlagFinished:(unsigned long long)arg1;
+ (unsigned long long)readValueFromFile;
+ (void)InitMMDBMigration:(id)arg1 UsrName:(id)arg2;

@end

