//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMDiskUsageRepoterDelegate.h"
#import "MMDiskUsageScannerDelegate.h"
#import "MMService.h"
#import "ReportStrategyExt.h"

@class MMDiskUsageConfigHandler, MMDiskUsageReporter, MMDiskUsageScaner, MMDiskUsageStatus, MMTimer, NSObject<OS_dispatch_queue>, NSString;

@interface MMDiskUsageMgr : MMService <MMDiskUsageScannerDelegate, MMDiskUsageRepoterDelegate, ReportStrategyExt, MMService>
{
    NSObject<OS_dispatch_queue> *m_workQueue;
    MMTimer *m_timerStartScan;
    MMTimer *m_timerStopScan;
    MMDiskUsageScaner *m_scanner;
    MMDiskUsageReporter *m_reporter;
    MMDiskUsageConfigHandler *m_configHandler;
    MMDiskUsageStatus *m_status;
}

@property(retain, nonatomic) MMDiskUsageStatus *m_status; // @synthesize m_status;
@property(retain, nonatomic) MMDiskUsageConfigHandler *m_configHandler; // @synthesize m_configHandler;
@property(retain, nonatomic) MMDiskUsageReporter *m_reporter; // @synthesize m_reporter;
@property(retain, nonatomic) MMDiskUsageScaner *m_scanner; // @synthesize m_scanner;
@property(retain, nonatomic) MMTimer *m_timerStopScan; // @synthesize m_timerStopScan;
@property(retain, nonatomic) MMTimer *m_timerStartScan; // @synthesize m_timerStartScan;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *m_workQueue; // @synthesize m_workQueue;
- (void).cxx_destruct;
- (void)onReceiveStrategy:(int)arg1 withContene:(id)arg2;
- (void)onDiskUsageScanStop;
- (void)onDiskUsageScanStart;
- (void)onTimerStopScan;
- (void)invalidateTimerStopScan;
- (void)scheduleTimerStopScan;
- (void)onTimerStartScan;
- (void)invalidateTimerStartScan;
- (void)scheduleTimerStartScan;
- (id)generateScanConfig;
- (_Bool)isTimeToScan;
- (_Bool)isScanRunning;
- (void)immediateStopScanDisk;
- (void)stopScanDisk;
- (void)startScanDisk;
- (void)scanPhase;
- (void)onReportFinished;
- (void)report;
- (_Bool)isNeedReport;
- (_Bool)isTimeToReport;
- (_Bool)isReporterRunning;
- (void)setupReporter;
- (void)reportPhase;
- (void)saveStatus;
- (void)loadStatus;
- (_Bool)isReadyToRun;
- (void)createWorkQueue;
- (void)ReceiveStrategyConfigXml:(id)arg1;
- (void)onServiceTerminate;
- (void)onServiceEnterBackground;
- (void)onServiceEnterForeground;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)clearReportAndScanData;
- (void)clearData;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

