//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMComponent.h"

@class MMUIImageView;

@interface MMFavHeadComponent : MMComponent
{
    MMUIImageView *_headImgView;
}

+ (double)calHeightWithComData:(id)arg1;
- (void).cxx_destruct;
- (void)dealloc;
- (void)configContentLayout;
- (void)configHeadImgView;

@end

