//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMHorizontalTableView;

@protocol MMHorizontalTableViewDelegate <NSObject>
- (double)horizontalTableView:(MMHorizontalTableView *)arg1 widthForColumnAtIndex:(unsigned long long)arg2;
- (void)horizontalTableView:(MMHorizontalTableView *)arg1 didSelectColumnAtIndex:(unsigned long long)arg2;
@end

