//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

@interface MMMusicPlayerModeTipView : UIView
{
    UIView *m_bkgView;
    UILabel *m_label;
}

- (void).cxx_destruct;
- (void)fadeShowWithDuration:(double)arg1;
- (id)initWithFrame:(struct CGRect)arg1 tipText:(id)arg2;

@end

