//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol MMPickerViewDelegate <NSObject>

@optional
- (void)MMPickerViewDidChooseRowTitle:(NSString *)arg1 atSessionTitle:(NSString *)arg2;
- (void)MMPickerViewDidChooseRow:(long long)arg1 atSession:(long long)arg2;
- (void)MMPickerViewDidCancel;
@end

