//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CAShapeLayer.h"

@interface MMProgressViewExLayer : CAShapeLayer
{
    double angle;
}

+ (_Bool)needsDisplayForKey:(id)arg1;
@property(nonatomic) double angle; // @synthesize angle;
- (void)drawInContext:(struct CGContext *)arg1;
- (id)initWithLayer:(id)arg1;

@end

