//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MMSessionFileItem : NSObject
{
}

+ (id)fromData:(id)arg1;
+ (_Bool)deleteSessionOfUser:(id)arg1;
+ (id)loadSessionOfUser:(id)arg1;
+ (_Bool)saveSession:(id)arg1;

@end

