//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ShortVideoBarDelegate.h"

@class NSString, ShortVideoToolbar;

@interface MMSightCameraViewController : MMUIViewController <ShortVideoBarDelegate>
{
    id <MMSightCameraViewControllerDelegate> _delegate;
    ShortVideoToolbar *_shortVideoToolbar;
    unsigned long long _cameraMode;
    unsigned long long _scene;
}

@property(nonatomic) unsigned long long scene; // @synthesize scene=_scene;
@property(nonatomic) unsigned long long cameraMode; // @synthesize cameraMode=_cameraMode;
@property(retain, nonatomic) ShortVideoToolbar *shortVideoToolbar; // @synthesize shortVideoToolbar=_shortVideoToolbar;
@property(nonatomic) __weak id <MMSightCameraViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)sightCameraViewControllerDidRotate:(id)arg1;
- (id)chatUserNameForSightStatistics;
- (void)onCameraResign;
- (void)onSightPictureTaken:(id)arg1 withFrontCamera:(_Bool)arg2;
- (void)handleShortVideoWithPath:(id)arg1 thumbImg:(id)arg2 sentImmediately:(_Bool)arg3 isMuted:(_Bool)arg4;
- (void)onShortVideoTaken:(id)arg1 thumbImg:(id)arg2 sentImmediately:(_Bool)arg3 isMuted:(_Bool)arg4;
- (void)onShortVideoToolBtnClick:(int)arg1;
- (void)close;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)didEnterBackground;
- (id)initWithCameraMode:(unsigned long long)arg1 scene:(int)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

