//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMSMBaseViewController.h"

@interface MMSMRebootViewController : MMSMBaseViewController
{
    int _controllerType;
}

@property(nonatomic) int controllerType; // @synthesize controllerType=_controllerType;
- (void)onNextButtonClicked:(id)arg1;
- (void)onRebootButtonClicked:(id)arg1;
- (void)viewDidLoad;
- (id)init;

@end

