//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSSet, UIEvent;

@protocol MMTransparentButtonDelegate <NSObject>

@optional
- (void)MMTransparentButton_touchesCancelled:(NSSet *)arg1 withEvent:(UIEvent *)arg2;
- (void)MMTransparentButton_touchesEnded:(NSSet *)arg1 withEvent:(UIEvent *)arg2;
- (void)MMTransparentButton_touchesMoved:(NSSet *)arg1 withEvent:(UIEvent *)arg2;
- (void)MMTransparentButton_touchesBegan:(NSSet *)arg1 withEvent:(UIEvent *)arg2;
@end

