//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@interface MMUILongPressView : MMUIView
{
    _Bool m_bIsLongPressHandled;
    double m_fLongPressTime;
    id <LongPressViewDelegate> _delegate;
}

@property(nonatomic) __weak id <LongPressViewDelegate> m_delegate; // @synthesize m_delegate=_delegate;
@property(nonatomic) double m_fLongPressTime; // @synthesize m_fLongPressTime;
- (void).cxx_destruct;
- (void)LongPressEvents;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;

@end

