//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "MMSearchBarDelegate.h"
#import "RichTextLayoutDelegate.h"

@class MMLoadingView, MMSearchBar, NSMutableArray, NSString, SGCustomButton, UIButton;

@interface MsgSearchHelper : MMObject <RichTextLayoutDelegate, MMSearchBarDelegate>
{
    _Bool m_bStartSearch;
    _Bool m_bSearchBarBecomeFirstRespones;
    _Bool m_bSearchBarCancelBtnDown;
    NSMutableArray *m_arrSearchResult;
    MMSearchBar *m_oSearchBar;
    MMLoadingView *m_oLoadingView;
    UIButton *backGroundButton;
    UIButton *cancelButton;
    int m_eMsgSearchHelperScene;
    id <MsgSearchHelperDelegate> m_delegate;
    SGCustomButton *m_searchByName;
    SGCustomButton *m_searchByTime;
    _Bool _m_bShowSearchByName;
    _Bool _m_bShowSearchByTime;
}

@property(nonatomic) _Bool m_bShowSearchByTime; // @synthesize m_bShowSearchByTime=_m_bShowSearchByTime;
@property(nonatomic) _Bool m_bShowSearchByName; // @synthesize m_bShowSearchByName=_m_bShowSearchByName;
@property(nonatomic) int m_eMsgSearchHelperScene; // @synthesize m_eMsgSearchHelperScene;
@property(nonatomic) __weak id <MsgSearchHelperDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (_Bool)isSearchBarActive;
- (void)startSearch;
- (void)dealloc;
- (void)mmSearchDisplayControllerWillEndSearch;
- (void)mmSearchDisplayControllerWillBeginSearch;
- (void)cancelBtnDown;
- (void)mmSearchDisplayControllerDidBeginSearch;
- (void)mmSearchBarTextDidChange:(id)arg1;
- (void)mmsearchBarTextDidBeginEditing:(id)arg1;
- (void)mmsearchBarSearchButtonClicked:(id)arg1;
- (void)finishSearch;
- (void)cancelSearch;
- (void)doSearch:(id)arg1 Pre:(_Bool)arg2;
- (void)didSearchViewTableSelect:(id)arg1;
- (double)heightForSearchViewTable:(id)arg1;
- (id)cellForSearchViewTable:(id)arg1 index:(id)arg2;
- (_Bool)shouldOpenNewLineAtY:(double)arg1 withLineHeight:(double)arg2 richTextView:(id)arg3;
- (void)startSearch:(id)arg1;
- (void)fillSearcLoadMoreCell:(id)arg1;
- (void)fillSearcResultCell:(id)arg1 MessageWrap:(id)arg2;
- (void)fillSearchWordingCell:(id)arg1 withSearchText:(id)arg2;
- (id)searchDisplayController;
- (id)searchBar;
- (_Bool)searchBarShouldBecomeFirstResponse;
- (void)resetBackGroundView;
- (void)reloadView;
- (void)searchByTime;
- (void)searchByName;
- (void)initBackGroundView;
- (void)searchBarResignFirstResponder;
- (id)initWithContentsController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

