//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton;

@interface MultitalkSecondOperateView : UIView
{
    id <MultitalkSecondOperateViewDelegate> _m_delegate;
    UIButton *_m_addMemberButton;
    UIButton *_m_minimizeButton;
}

@property(retain, nonatomic) UIButton *m_minimizeButton; // @synthesize m_minimizeButton=_m_minimizeButton;
@property(retain, nonatomic) UIButton *m_addMemberButton; // @synthesize m_addMemberButton=_m_addMemberButton;
@property(nonatomic) __weak id <MultitalkSecondOperateViewDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
- (void).cxx_destruct;
- (void)onMinimizeButtonClick;
- (void)onAddMemberButtonClick;
- (void)initAddMemberButton;
- (void)initMinimizeButton;
- (void)initButtonBgBarView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)updateAddMemberEnabled:(_Bool)arg1;
- (void)showOperateView;
- (void)hideOperateView;

@end

