//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBCoding.h"

@class NSString;

@interface NewUserGuideConfig : NSObject <PBCoding>
{
    _Bool bShowMainFrameTip;
    _Bool bShowContactsAddTip;
    _Bool bShowVoiceTip;
    _Bool bShowVoipAndPhoneTip;
    _Bool bShowNearByRedDot;
    _Bool bShowShakeRedDot;
    _Bool bShowSightTip;
    unsigned int uiRegTime;
    unsigned int uiStartCount;
}

+ (void)initialize;
@property(nonatomic) _Bool bShowSightTip; // @synthesize bShowSightTip;
@property(nonatomic) _Bool bShowShakeRedDot; // @synthesize bShowShakeRedDot;
@property(nonatomic) _Bool bShowNearByRedDot; // @synthesize bShowNearByRedDot;
@property(nonatomic) _Bool bShowVoipAndPhoneTip; // @synthesize bShowVoipAndPhoneTip;
@property(nonatomic) _Bool bShowVoiceTip; // @synthesize bShowVoiceTip;
@property(nonatomic) _Bool bShowContactsAddTip; // @synthesize bShowContactsAddTip;
@property(nonatomic) _Bool bShowMainFrameTip; // @synthesize bShowMainFrameTip;
@property(nonatomic) unsigned int uiStartCount; // @synthesize uiStartCount;
@property(nonatomic) unsigned int uiRegTime; // @synthesize uiRegTime;
- (id)init;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

