//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface NewYearScanReportRequest2017 : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *appUserName; // @dynamic appUserName;
@property(nonatomic) unsigned int checksum; // @dynamic checksum;
@property(nonatomic) unsigned int clientVersion; // @dynamic clientVersion;
@property(nonatomic) unsigned int deviceType; // @dynamic deviceType;
@property(nonatomic) unsigned int scene; // @dynamic scene;

@end

