//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (WXCBase64Addtion)
+ (id)decodeWebSafeBase64ForString:(id)arg1;
+ (id)decodeBase64ForString:(id)arg1;
- (id)encodeWebSafeBase64ForData;
- (id)encodeBase64ForData;
@end

