//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (strup)
+ (id)intToConvertBinaryString:(int)arg1;
+ (id)mimeTypeForFileAtPath:(id)arg1;
- (id)getContentAndRangeFromAttributeString;
- (id)dropAeraCode;
- (id)formatChinaPhoneString:(id)arg1;
- (_Bool)isEmailAddress;
- (_Bool)isMobilePhone;
- (_Bool)isCurrectPhoneNum;
- (_Bool)isNumericStr;
- (id)XXXString;
- (id)dropHead:(id)arg1;
- (_Bool)checkIsLegalMobile:(unsigned short *)arg1 bufLen:(int)arg2;
- (id)getTelPhoneNumberAreaString:(_Bool *)arg1;
- (id)GetTelPhoneNumberAreaString;
- (id)getTelPhoneNumbersWithComma;
- (id)GetTelPhoneNumber;
@end

