//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QOverlayPathView.h"

@class QPolyline;

@interface QPolylineView : QOverlayPathView
{
}

- (id)initWithPolyline:(id)arg1;
- (void)setFillColor:(id)arg1;
- (void)createPath;
@property(readonly, nonatomic) QPolyline *polyline;

@end

