//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class NSString, UIButton, UIImageView, UILabel;

@interface QQEmojiViewWithPreview : MMUIView
{
    UIButton *m_emojiButton;
    UIImageView *m_emojiPreviewBackView;
    UILabel *m_emojiDescriptionLabel;
    UIButton *m_emojiPreviewView;
    NSString *m_emojiKey;
    _Bool _needReloadPreview;
}

@property(nonatomic) _Bool needReloadPreview; // @synthesize needReloadPreview=_needReloadPreview;
@property(retain, nonatomic) UIButton *m_emojiButton; // @synthesize m_emojiButton;
@property(retain, nonatomic) UIButton *m_emojiPreviewView; // @synthesize m_emojiPreviewView;
@property(retain, nonatomic) UIImageView *m_emojiPreviewBackView; // @synthesize m_emojiPreviewBackView;
@property(retain, nonatomic) NSString *m_emojiKey; // @synthesize m_emojiKey;
@property(retain, nonatomic) UILabel *m_emojiDescriptionLabel; // @synthesize m_emojiDescriptionLabel;
- (void).cxx_destruct;
- (void)reloadButton;
- (void)reloadPreview;
- (void)hidePreview;
- (void)showPreview;
- (void)changeKey:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 EmojiKey:(id)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

