//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface QstrInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *passWord; // @dynamic passWord;
@property(nonatomic) unsigned int protocolType; // @dynamic protocolType;
@property(retain, nonatomic) NSString *ssid; // @dynamic ssid;

@end

