//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface RankItem : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *label; // @dynamic label;
@property(nonatomic) unsigned int rank; // @dynamic rank;
@property(nonatomic) unsigned long long score; // @dynamic score;
@property(retain, nonatomic) NSString *timeScoreDesc; // @dynamic timeScoreDesc;
@property(nonatomic) _Bool upedByMe; // @dynamic upedByMe;
@property(nonatomic) int upedCount; // @dynamic upedCount;
@property(retain, nonatomic) NSString *userName; // @dynamic userName;

@end

