//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class BaseRequest, SKBuiltinBuffer_t;

@interface RegisterNewPatternLockRequest : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) BaseRequest *baseRequest; // @dynamic baseRequest;
@property(nonatomic) unsigned int cmd; // @dynamic cmd;
@property(retain, nonatomic) SKBuiltinBuffer_t *patternhash; // @dynamic patternhash;
@property(retain, nonatomic) SKBuiltinBuffer_t *paytoken; // @dynamic paytoken;

@end

