//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSRecursiveLock, NSThread;

@interface ResourceMonitor : MMObject
{
    id <ResourceMonitorDelegate> _delegate;
    NSThread *_monitorThread;
    NSRecursiveLock *_lock;
    _Bool _monitoring;
    int m_nCnt;
}

@property(nonatomic) __weak id <ResourceMonitorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;
- (void)startService;
- (void)threadFunc;
- (void)updateResourceInfo:(id)arg1;
- (void)stopService;

@end

