//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class BaseRequest, NSString;

@interface RevokeMsgRequest : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) BaseRequest *baseRequest; // @dynamic baseRequest;
@property(retain, nonatomic) NSString *clientMsgId; // @dynamic clientMsgId;
@property(nonatomic) unsigned int createTime; // @dynamic createTime;
@property(retain, nonatomic) NSString *fromUserName; // @dynamic fromUserName;
@property(nonatomic) unsigned int indexOfRequest; // @dynamic indexOfRequest;
@property(nonatomic) unsigned int newClientMsgId; // @dynamic newClientMsgId;
@property(nonatomic) unsigned int svrMsgId; // @dynamic svrMsgId;
@property(nonatomic) unsigned long long svrNewMsgId; // @dynamic svrNewMsgId;
@property(retain, nonatomic) NSString *toUserName; // @dynamic toUserName;

@end

