//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface RSAEncryptObject : NSObject
{
    NSString *_m_publicPemKey;
}

@property(retain, nonatomic) NSString *m_publicPemKey; // @synthesize m_publicPemKey=_m_publicPemKey;
- (void).cxx_destruct;
- (id)encryptWithSourceString:(id)arg1;
- (id)initWithRSAPublicPemKey:(id)arg1;

@end

