//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseScanLogicController.h"

#import "IScanStreetViewMgrExt.h"
#import "LocationRetrieveDelegate.h"
#import "MMWebViewDelegate.h"
#import "UIAlertViewDelegate.h"
#import "WCActionSheetDelegate.h"

@class CLLocation, LocationRetriever, MMWebViewController, NSString;

@interface ScanStreetViewLogicController : BaseScanLogicController <IScanStreetViewMgrExt, LocationRetrieveDelegate, MMWebViewDelegate, WCActionSheetDelegate, UIAlertViewDelegate>
{
    MMWebViewController *_webViewController;
    int _retryCount;
    CLLocation *_location;
    LocationRetriever *_locationRetriever;
    NSString *_streetViewUrl;
    NSString *_alertText;
    _Bool _shouldShowScanAnimation;
}

- (void).cxx_destruct;
- (void)onWebViewDidFinishLoad:(id)arg1;
- (void)checkAllReady;
- (void)onRetrieveLocationError:(int)arg1;
- (void)onRetrieveLocationTimeOut:(id)arg1;
- (void)onRetrieveLocationOK:(id)arg1;
- (void)OnSendStreetViewLocation:(id)arg1 Err:(int)arg2;
- (void)stopLocating;
- (void)startLocating;
- (_Bool)shouldStartScanAnimation;
- (_Bool)shouldHideAlertOnClicked;
- (id)getAlertText;
- (id)getInfoText;
- (struct CGRect)getDrawCropRect;
- (void)stopScan;
- (void)startScan;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

