//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITextFieldDelegate.h"

@class NSMutableArray, NSString, UITextField;

@interface ScanLicenceBankCardEditView : UIView <UITextFieldDelegate>
{
    NSMutableArray *_arrTextField;
    UITextField *bankSequenceField;
}

- (void).cxx_destruct;
- (id)getFullBankNumStr;
- (void)textFieldDidBeginEditing:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 andCodeNum:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

