//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBCoding.h"

@class NSString;

@interface SearchGuideVertEntryData : NSObject <PBCoding>
{
    unsigned int opType;
    unsigned long long businessType;
    NSString *title;
}

+ (void)initialize;
@property(nonatomic) unsigned int opType; // @synthesize opType;
@property(retain, nonatomic) NSString *title; // @synthesize title;
@property(nonatomic) unsigned long long businessType; // @synthesize businessType;
- (void).cxx_destruct;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

