//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface ShowWordsInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *respShowWordsEn; // @dynamic respShowWordsEn;
@property(retain, nonatomic) NSString *respShowWordsZhcn; // @dynamic respShowWordsZhcn;
@property(retain, nonatomic) NSString *respShowWordsZhtw; // @dynamic respShowWordsZhtw;

@end

