//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SightDraft;

@protocol SightDraftBoxDelegate <NSObject>

@optional
- (void)onPlayerCleared;
- (void)onUndo;
- (void)onItemDeleted;
- (void)onItemChecked:(long long)arg1 withSightDraft:(SightDraft *)arg2;
- (void)onItemClicked:(long long)arg1 withSightDraft:(SightDraft *)arg2;
- (void)onItemLongClicked:(long long)arg1;
@end

