//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "BlockViewControllerDelegate.h"
#import "IPreEnterWechatLogicExt.h"
#import "PBMessageObserverDelegate.h"

@class BlockViewController, NSString, NSURL;

@interface SMSAddCardHandler : MMObject <BlockViewControllerDelegate, PBMessageObserverDelegate, IPreEnterWechatLogicExt>
{
    NSURL *_infoUrl;
    BlockViewController *_blockView;
}

- (void).cxx_destruct;
- (void)onBlockViewControllerReturn;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)handleSMSAddCard:(id)arg1;
- (void)createWechatSMSAddCard;
- (void)onPreEnterWechatDone;
- (void)cancelCheckAndAddCard;
- (void)startCheckAndAddCard:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

