//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface StatisticsSnsAdInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;
- (_Bool)isVaild;

// Remaining properties
@property(retain, nonatomic) NSString *adPublishId; // @dynamic adPublishId;
@property(nonatomic) unsigned int adType; // @dynamic adType;
@property(retain, nonatomic) NSString *adUxInfo; // @dynamic adUxInfo;
@property(retain, nonatomic) NSString *snsStatExt; // @dynamic snsStatExt;
@property(nonatomic) unsigned int source; // @dynamic source;

@end

