//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSSet, UIEvent;

@protocol tableViewDelegate <NSObject>

@optional
- (void)didFinishedLoading:(id)arg1;
- (void)touchesCancelled_TableView:(NSSet *)arg1 withEvent:(UIEvent *)arg2;
- (void)touchesEnded_TableView:(NSSet *)arg1 withEvent:(UIEvent *)arg2;
- (void)touchesMoved_TableView:(NSSet *)arg1 withEvent:(UIEvent *)arg2;
- (void)touchesBegan_TableView:(NSSet *)arg1 withEvent:(UIEvent *)arg2;
@end

