//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GetTrustedFriendsResp, NSArray, NSString;

@protocol TrustedFriendsCgiDelegate <NSObject>
- (void)onSyncTrustedFriendsSuccess:(NSArray *)arg1;
- (void)onGetTrustedFriendsListSuccess:(GetTrustedFriendsResp *)arg1;
- (void)onCgiFailed:(unsigned int)arg1 error:(int)arg2 msg:(NSString *)arg3;
@end

