//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class NSArray, NSString;

@interface TwoDDecoderResult : NSObject <NSCopying>
{
    NSString *text;
    NSArray *points;
}

+ (id)resultWithText:(id)arg1 points:(id)arg2;
@property(retain, nonatomic) NSArray *points; // @synthesize points;
@property(retain, nonatomic) NSString *text; // @synthesize text;
- (void).cxx_destruct;
- (id)description;
- (id)copy;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithText:(id)arg1 points:(id)arg2;

@end

