//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImage.h"

@interface UIImage (ExtendForWatch)
- (id)resizeIfNeedMaxWidth:(int)arg1 andMaxHeight:(int)arg2;
@end

