//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface UploadFileRecord : MMObject
{
    unsigned int _type;
    NSString *_weburl;
}

@property(nonatomic) unsigned int type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *weburl; // @synthesize weburl=_weburl;
- (void).cxx_destruct;

@end

