//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CMessageWrap, NSString;

@protocol UploadImageCDNMgrDelegate <NSObject>

@optional
- (void)onUploadImageCheckQQ;
- (void)onUploadImageModMsg:(NSString *)arg1 MsgWrap:(CMessageWrap *)arg2;
- (void)onUploadImageModMsgByBitSet:(NSString *)arg1 MsgWrap:(CMessageWrap *)arg2 BitSet:(unsigned int)arg3;
@end

