//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MassSendWrap;

@protocol UploadShortVideoDelegate <NSObject>
- (void)UploadMassShortVideoFail:(MassSendWrap *)arg1;
- (void)UploadMassShortVideoUploadOK:(MassSendWrap *)arg1;
- (void)UploadMassShortVideoOK:(MassSendWrap *)arg1;
- (void)UploadMassShortVideoProgress:(MassSendWrap *)arg1 finishedLen:(int)arg2 totalLen:(int)arg3;
@end

