//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CommonMessageCellView.h"

#import "ChatBackgroundExt.h"
#import "IMsgRevokeExt.h"
#import "MMTipsViewControllerDelegate.h"
#import "VoiceTransFloatViewDelegate.h"

@class MMTipsViewController, NSString, UIImageView, UILabel, VoiceMessageViewModel, VoiceTransFloatPreview;

@interface VoiceMessageCellView : CommonMessageCellView <ChatBackgroundExt, IMsgRevokeExt, MMTipsViewControllerDelegate, VoiceTransFloatViewDelegate>
{
    double m_currVoiceTimeLength;
    UILabel *m_secLabel;
    UIImageView *m_playingImageView;
    UIImageView *m_recordingView;
    UIImageView *m_unreadImageView;
    MMTipsViewController *m_voiceTransIntro;
    VoiceTransFloatPreview *m_voiceTransFloatPreview;
}

- (void).cxx_destruct;
- (void)onWindowHide;
- (void)onTransComplete;
- (void)onClickTipsBtn:(unsigned long long)arg1;
- (void)onChatBackgroundChanged:(id)arg1;
- (void)OnMsgRevoked:(id)arg1 n64MsgId:(long long)arg2 SysMsg:(id)arg3;
- (void)updateVoiceLength;
- (void)updateSecLabelColor;
- (void)stopPlaying;
- (void)startPlaying;
- (void)onClick;
- (void)onTouchUpInside;
- (void)onTouchDown;
- (void)showVoiceTransView;
- (void)onVoiceTrans:(id)arg1;
- (void)onSwitch:(id)arg1;
- (_Bool)canShowVoiceTransMenu;
- (id)operationMenuItems;
- (void)initUnreadView;
- (void)initRecordingView;
- (void)initPlayingImageView;
- (void)initSecLabel;
- (void)setFrameForBgImageView:(struct CGRect)arg1;
- (void)onAppear;
- (void)updateStatus;
- (void)layoutContentView;
- (void)dealloc;
- (id)initWithViewModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, nonatomic) VoiceMessageViewModel *viewModel; // @dynamic viewModel;

@end

