//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBCoding.h"

@class NSMutableArray, NSString;

@interface VOIPRecentConnect : NSObject <PBCoding>
{
    NSMutableArray *m_videoRecentConnectUserName;
    NSMutableArray *m_voiceRecentConnectUserName;
}

+ (id)loadFromFile;
+ (id)getSavePath;
+ (id)getSaveRootDir;
+ (void)initialize;
@property(retain, nonatomic) NSMutableArray *m_voiceRecentConnectUserName; // @synthesize m_voiceRecentConnectUserName;
@property(retain, nonatomic) NSMutableArray *m_videoRecentConnectUserName; // @synthesize m_videoRecentConnectUserName;
- (void).cxx_destruct;
- (void)saveToCache;
- (void)dealloc;
- (void)addRecentVoiceConnect:(id)arg1;
- (void)addRecentVideoConnect:(id)arg1;
- (id)getRecentVoiceContact;
- (id)getRecentVideoConnect;
- (id)init;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

