//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class BaseResponse, NSData, NSMutableArray;

@interface VoipCSInviteResp : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *addrList; // @dynamic addrList;
@property(retain, nonatomic) BaseResponse *baseResponse; // @dynamic baseResponse;
@property(nonatomic) unsigned int checkPeerCnt; // @dynamic checkPeerCnt;
@property(nonatomic) unsigned int checkPeerInterval; // @dynamic checkPeerInterval;
@property(retain, nonatomic) NSData *encryptKeyBuf; // @dynamic encryptKeyBuf;
@property(nonatomic) unsigned int encryptStrategy; // @dynamic encryptStrategy;
@property(nonatomic) unsigned int maxBitRate; // @dynamic maxBitRate;
@property(nonatomic) unsigned int maxFps; // @dynamic maxFps;
@property(nonatomic) unsigned int nextInvite; // @dynamic nextInvite;
@property(nonatomic) unsigned long long roomId; // @dynamic roomId;
@property(nonatomic) unsigned long long roomKey; // @dynamic roomKey;
@property(nonatomic) unsigned int syncInterval; // @dynamic syncInterval;

@end

