//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, UILabel, UITableView;

@interface WABrandBindWeAppListViewController : MMUIViewController <UITableViewDelegate, UITableViewDataSource>
{
    UILabel *_contentLabel;
    UITableView *_listTableView;
    NSArray *_arrBindWeAppInfo;
    NSString *_fromBrandUserName;
}

@property(retain, nonatomic) NSString *fromBrandUserName; // @synthesize fromBrandUserName=_fromBrandUserName;
@property(retain, nonatomic) NSArray *arrBindWeAppInfo; // @synthesize arrBindWeAppInfo=_arrBindWeAppInfo;
- (void).cxx_destruct;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)onBackButtonClicked:(id)arg1;
- (void)layoutMySubViews;
- (void)viewDidLayoutSubviews;
- (void)initTableView;
- (void)initContentLabel;
- (void)initView;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

