//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMConfigMgrExt.h"
#import "MMKernelExt.h"
#import "MMService.h"
#import "PBMessageObserverDelegate.h"

@class NSMutableArray, NSMutableDictionary, NSMutableSet, NSString;

@interface WAContactMgr : MMService <MMConfigMgrExt, PBMessageObserverDelegate, MMKernelExt, MMService>
{
    NSMutableDictionary *_dicContactCache;
    NSMutableArray *_arrSingleAttrSyncWait;
    NSMutableSet *_setSingleAttrSyncRequest;
    unsigned int _singleAttrSyncRequestInterval;
    NSMutableArray *_arrBatchAttrSyncWait;
    NSMutableSet *_setBatchAttrSyncRequest;
    unsigned int _batchAttrSyncRequestInterval;
    _Bool _isLoadAllFocusContact;
}

@property _Bool isLoadAllFocusContact; // @synthesize isLoadAllFocusContact=_isLoadAllFocusContact;
- (void).cxx_destruct;
- (void)updateFocusContactAfterInitOK;
- (void)onInitOK;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)onResponseAddWxApp:(id)arg1;
- (void)processBatchBizAttrSyncResponse:(id)arg1;
- (void)onResponseBatchBizAttrSync:(id)arg1;
- (_Bool)requestBatchBizAttrSync:(id)arg1 versionList:(id)arg2;
- (void)checkBatchBizAttrSyncWaitQueue;
- (void)mainThread_batchUpdateWeAppContact:(id)arg1;
- (void)setHeadImageStatusForNewContact:(id)arg1 withOldContact:(id)arg2;
- (void)processBizAttrSyncResponse:(id)arg1 withRequest:(id)arg2;
- (void)onResponseBizAttrSync:(id)arg1;
- (_Bool)requestBizAttrSync:(id)arg1;
- (void)checkBizAttrSyncWaitQueue;
- (void)mainThread_updateWeAppContact:(id)arg1;
- (void)clearBizAttrSyncBufferTime:(id)arg1;
- (void)updateContact:(id)arg1 withBizAttr:(id)arg2;
- (id)getNewContactWithUserName:(id)arg1 bizAttr:(id)arg2;
- (void)loadBizAttrSyncRequestInterval;
- (void)onMMDynamicConfigUpdated;
- (void)removeContactListInCache:(id)arg1;
- (void)setAllFocusContactListToCache:(id)arg1;
- (void)setContactListToCache:(id)arg1;
- (id)getAllFocusContactFromCache;
- (id)getContactFromCache:(id)arg1;
- (void)callExtensionDeleteContact:(id)arg1;
- (void)callExtensionModifyContact:(id)arg1;
- (_Bool)updateContactListToDBAndCallModify:(id)arg1;
- (void)updateContactCacheAndCallModifyContact:(id)arg1;
- (void)thread_onServerDelContact:(id)arg1;
- (void)thread_onServerModContactList:(id)arg1;
- (_Bool)modifyHeadImageStatus:(id)arg1 withUserName:(id)arg2;
- (_Bool)modifyWxAppOptWithBitMask:(unsigned int)arg1 bitValue:(unsigned int)arg2 userName:(id)arg3;
- (void)unfocusWeAppContact:(id)arg1;
- (_Bool)focusWeAppContact:(id)arg1 scene:(unsigned int)arg2 qrcodeScene:(unsigned int)arg3;
- (void)batchUpdateWeAppContact:(id)arg1;
- (void)updateWeAppContact:(id)arg1 isForce:(_Bool)arg2;
- (void)updateWeAppContact:(id)arg1;
- (_Bool)hasContact:(id)arg1;
- (void)deleteWeAppContactList:(id)arg1;
- (id)getAllWeAppContact;
- (id)getAllNoFocusWeAppContact;
- (id)getAllFocusWeAppContact;
- (id)getWeAppContact:(id)arg1;
- (void)onServiceClearData;
- (void)onServiceReloadData;
- (void)onServiceInit;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

