//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "WKNavigationDelegate.h"

@class NSString, UITapGestureRecognizer, WKWebView;

@interface WAFileViewController : MMUIViewController <UIScrollViewDelegate, WKNavigationDelegate, UIGestureRecognizerDelegate>
{
    UITapGestureRecognizer *_singleTapRec;
    _Bool _bIsNaviBarHide;
    WKWebView *_webView;
    NSString *_filePath;
}

@property(copy, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(retain, nonatomic) WKWebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;
- (void)webViewWebContentProcessDidTerminate:(id)arg1;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didCommitNavigation:(id)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (id)initWithDocument:(id)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)onSingleTap:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setNaviBarHide:(_Bool)arg1 animation:(_Bool)arg2;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

