//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAJSEventHandler_getStorage.h"

@interface WAJSEventHandler_getStorageSync : WAJSEventHandler_getStorage
{
}

- (void)handleJSEvent:(id)arg1;

@end

