//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAWebViewPluginBase.h"

#import "IAudioPlayerDelegate.h"

@class NSString, WAAudioPlayer;

@interface WAWebViewPlugin_playAudio : WAWebViewPluginBase <IAudioPlayerDelegate>
{
    WAAudioPlayer *_player;
}

@property(retain, nonatomic) WAAudioPlayer *player; // @synthesize player=_player;
- (void).cxx_destruct;
- (void)onAudioEnd;
- (void)onAudioUpdate:(CDStruct_1b6d18a9)arg1 total:(CDStruct_1b6d18a9)arg2;
- (void)onAudioPause;
- (void)onAudioPlay;
- (_Bool)handleEvent:(unsigned long long)arg1 userInfo:(id)arg2;
- (void)resumeAudio;
- (void)pauseAudio;
- (void)stopAudio;
- (void)enterBackground;
- (void)enterForeground;
- (void)playAudio:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

