//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCAccountBaseViewController.h"

#import "MMKernelExt.h"
#import "PushLoginURLCGIDelegate.h"
#import "UIAlertViewDelegate.h"
#import "WCActionSheetDelegate.h"

@class NSString, PushLoginURLCGI, UIActivityIndicatorView, UIButton, UIImageView, UILabel;

@interface WCAccountOneClickLoginViewController : WCAccountBaseViewController <PushLoginURLCGIDelegate, MMKernelExt, UIAlertViewDelegate, WCActionSheetDelegate>
{
    UIImageView *_headImgView;
    UILabel *_tipsLabel;
    UILabel *_nickNameLabel;
    UIButton *_loginBtn;
    UIButton *_disconnectBtn;
    UIButton *_switchAccountBtn;
    UIButton *_cancleLogin;
    UIActivityIndicatorView *_logingLoading;
    PushLoginURLCGI *_pushLoginURLCGI;
    _Bool _isDoingAuth;
    _Bool _isShowingPairView;
    id <WCAccountOneClickLoginViewControllerDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)onManulLoginOK;
- (void)setDelegate:(id)arg1;
- (void)cancleOneClickLogin;
- (void)loginByQRCode;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onPushLoginURLConfrimed;
- (void)onPushLoginURLCanceled;
- (void)onPushLoginURLSuccess;
- (void)onPushLoginURLFailedWithError:(int)arg1;
- (void)onLoginBtnClicked;
- (void)onOtherLoginMethodClicked;
- (void)onDisconnectBtnClicked;
- (void)showLoginingView;
- (id)getPushLoginURLCGI;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)viewDidAppear:(_Bool)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

