//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCAccountBaseControlLogic.h"

#import "PasswordLogicDelegate.h"
#import "WCAccountBindPhoneForRegCGIDelegate.h"
#import "WCAccountFillPhoneViewControllerDelegate.h"
#import "WCAccountManualAuthControlLogicDelegate.h"
#import "WCAccountPhoneVerifyViewControllerDelegate.h"
#import "WCAccountRegByOldPhoneViewControllerDelegate.h"
#import "WCAccountSetPasswordViewControllerDelegate.h"
#import "WCAccountVoiceVerifyViewControllerDelegate.h"
#import "WCBaseControlMgrExt.h"

@class NSString, PasswordLogic, WCAccountBindPhoneForRegCGI, WCAccountGraphicVerifyControlLogic, WCAccountManualAuthControlLogic, WCAccountSafeDeviceControlLogic;

@interface WCAccountPhoneLoginControlLogic : WCAccountBaseControlLogic <WCBaseControlMgrExt, WCAccountFillPhoneViewControllerDelegate, WCAccountVoiceVerifyViewControllerDelegate, WCAccountPhoneVerifyViewControllerDelegate, WCAccountSetPasswordViewControllerDelegate, WCAccountRegByOldPhoneViewControllerDelegate, PasswordLogicDelegate, WCAccountManualAuthControlLogicDelegate, WCAccountBindPhoneForRegCGIDelegate>
{
    unsigned int m_uiTryCount;
    _Bool m_bAdjustRet;
    _Bool m_bNeedSetPwd;
    WCAccountBindPhoneForRegCGI *m_modelLogic;
    WCAccountBaseControlLogic *m_subFBLogic;
    PasswordLogic *m_checkPasswdLogic;
    WCAccountSafeDeviceControlLogic *m_safeDeviceLogic;
    WCAccountGraphicVerifyControlLogic *m_graphicVerifyLogic;
    WCAccountManualAuthControlLogic *m_manualAuthLogic;
}

- (void).cxx_destruct;
- (void)DidEnterForeground:(id)arg1;
- (void)DidEnterBackground:(id)arg1;
- (void)resume;
- (void)pause;
- (_Bool)recoverFromArchive:(id)arg1;
- (id)getArchive;
- (void)onCheckForgetPwdVerifyCode:(id)arg1 userName:(id)arg2 password:(id)arg3 StyleKeyValue:(id)arg4;
- (void)onCheckLoginVerifyCode:(id)arg1 ticket:(id)arg2 controlShowFlag:(unsigned int)arg3 userName:(id)arg4 password:(id)arg5 StyleKeyValue:(id)arg6;
- (void)onCheckRegVerifyCode:(id)arg1 ticket:(id)arg2 controlShowFlag:(unsigned int)arg3 userName:(id)arg4 password:(id)arg5 StyleKeyValue:(id)arg6;
- (void)onGetForgetPwdVoiceVerifyCode:(id)arg1 StyleKeyValue:(id)arg2;
- (void)onGetLoginVoiceVerifyCode:(id)arg1 StyleKeyValue:(id)arg2;
- (void)onGetRegVoiceVerifyCode:(id)arg1 StyleKeyValue:(id)arg2;
- (void)onGetForgetPwdVerifyCode:(id)arg1 StyleKeyValue:(id)arg2;
- (void)onGetLoginVerifyCode:(id)arg1 StyleKeyValue:(id)arg2;
- (void)onGetRegVerifyCode:(id)arg1 StyleKeyValue:(id)arg2;
- (void)loginForPhone;
- (void)forceRegisterForPhone;
- (void)login_but_registerForPhone;
- (void)registerForPhone;
- (void)onGetVoiceVerifyCode:(id)arg1 StyleKeyValue:(id)arg2;
- (void)onGetVerifyCode:(id)arg1 StyleKeyValue:(id)arg2;
- (void)onCheckRegPhoneNumberStatus:(id)arg1 countryCode:(id)arg2 phoneNumber:(id)arg3 formatedPhoneNumber:(id)arg4 StyleKeyValue:(id)arg5;
- (void)onCheckLoginPhoneNumberStatus:(id)arg1 countryCode:(id)arg2 phoneNumber:(id)arg3 formatedPhoneNumber:(id)arg4 StyleKeyValue:(id)arg5;
- (_Bool)onManualAuthControlLogicError:(id)arg1;
- (void)onManualAuthControlLogicStop:(unsigned long long)arg1 response:(id)arg2;
- (void)onRegByOldPhoneLogin;
- (void)onRegByOldPhoneContinueReg;
- (void)onRegByOldPhoneBack;
- (void)checkHavePwd;
- (void)checkHaveNotSetPassword:(id)arg1;
- (void)checkHaveSetPassword:(id)arg1;
- (void)onSetPasswordOK;
- (void)onSetPasswordBack;
- (void)onSafeDeviceControlLogicReturnOK;
- (void)onSafeDeviceControlLogicCancel;
- (void)onVoiceVerifyGetVerifyCode:(id)arg1;
- (void)onVoiceVerifyBack;
- (void)onWCBaseLogicDidStop:(unsigned int)arg1;
- (void)onSignUpWithQQ;
- (void)onFacebookConnect;
- (void)onPhoneVerifyNext:(id)arg1;
- (void)onPhoneVerifyAgain;
- (void)onPhoneVerifyVoice;
- (void)onPhoneVerifyBack;
- (void)onByPhonePwdLoginByVerifyCode:(id)arg1 phoneNumber:(id)arg2;
- (void)onFillPhoneNext:(id)arg1 phoneNumber:(id)arg2 pwd:(id)arg3;
- (void)onFillPhoneNext:(id)arg1 phoneNumber:(id)arg2;
- (void)onFillPhoneBack;
- (void)onFillPhoneFromRegToLogin;
- (void)onFillPhoneLoginByQQ;
- (void)onFillPhoneGoToSecurityCenter;
- (void)onFillPhoneReg;
- (void)onLoginByQRCode;
- (void)loginAccount;
- (void)getVerifyCode;
- (_Bool)checkPhoneNumberStatus:(unsigned int)arg1;
- (_Bool)checkVerifyCode:(id)arg1;
- (_Bool)getVoideVerifyCodeReady:(id)arg1;
- (_Bool)getVerifyCodeReady;
- (void)cancelAllEvent;
- (void)startLogic;
- (id)initWithData:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

