//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol WCAccountBindPhoneSetPrivateViewControllerDelegate <NSObject>

@optional
- (void)onFillPhonePushFriendToMe:(_Bool)arg1;
- (void)onFillPhoneBindAgreeMobileCanBeFound:(_Bool)arg1;
- (void)onFillPhoneSetPrivateDone;
@end

