//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCADShareInfo : NSObject
{
    NSString *userName;
    unsigned int memberCount;
}

@property(nonatomic) unsigned int memberCount; // @synthesize memberCount;
@property(retain, nonatomic) NSString *userName; // @synthesize userName;
- (void).cxx_destruct;
- (id)init;

@end

