//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "WCDBCoding.h"

@class NSString;

@interface WCAdvertiseLogDBItem : MMObject <WCDBCoding>
{
    unsigned int m_uiLocalId;
    unsigned int m_uiCreateTime;
    unsigned int m_uiLogId;
    NSString *m_nsLogExt;
    long long m___rowID;
}

+ (const basic_string_a490aa4c *)getWCDBPrimaryColumnName;
+ (const struct WCDBIndexHelper *)getWCDBIndexArray;
+ (unsigned long long)getWCDBIndexArrayCount;
+ (const map_0e718273 *)getFileValueTagIndexMap;
+ (id)getFileValueTypeTable;
+ (const map_0e718273 *)getPackedValueTagIndexMap;
+ (id)getPackedValueTypeTable;
+ (const map_7a576766 *)getValueNameIndexMap;
+ (id)getValueTable;
+ (id)dummyObject;
@property(nonatomic) long long __rowID; // @synthesize __rowID=m___rowID;
@property(retain, nonatomic) NSString *m_nsLogExt; // @synthesize m_nsLogExt;
@property(nonatomic) unsigned int m_uiLogId; // @synthesize m_uiLogId;
@property(nonatomic) unsigned int m_uiCreateTime; // @synthesize m_uiCreateTime;
@property(nonatomic) unsigned int m_uiLocalId; // @synthesize m_uiLocalId;
- (void).cxx_destruct;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (const WCDBCondition_22fabacd *)db_m_nsLogExt;
- (const WCDBCondition_c6db074e *)db_m_uiLogId;
- (const WCDBCondition_c6db074e *)db_m_uiCreateTime;
- (const WCDBCondition_c6db074e *)db_m_uiLocalId;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

