//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@interface WCBeaconGatedLaunchOption : MMObject
{
    unsigned int tabState;
}

+ (void)initialize;
@property(nonatomic) unsigned int tabState; // @synthesize tabState;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;

@end

