//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString, UIImage;

@protocol WCCanvasImageLoaderObserver <NSObject>

@optional
- (void)ImageDidFail:(NSString *)arg1;
- (void)ImageDidLoadWithData:(NSData *)arg1 Url:(NSString *)arg2;
- (void)ImageDidLoad:(UIImage *)arg1 Url:(NSString *)arg2;
@end

