//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCCardPkgMsgJumpButton : NSObject
{
    NSString *_title;
    NSString *_desc;
    NSString *_buttonTitle;
    NSString *_jumpUrlStr;
}

@property(retain, nonatomic) NSString *jumpUrlStr; // @synthesize jumpUrlStr=_jumpUrlStr;
@property(retain, nonatomic) NSString *buttonTitle; // @synthesize buttonTitle=_buttonTitle;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)dealloc;

@end

