//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, WCCardAcceptCardInfo, WCCardBulkInfo;

@protocol WCCardBulkImportMgrDelegate <NSObject>

@optional
- (void)onImportBulkCard:(WCCardAcceptCardInfo *)arg1 errCode:(int)arg2;
- (void)onGetBulkInfo:(WCCardBulkInfo *)arg1 errCode:(int)arg2;
- (void)onGetBulkCard:(NSMutableArray *)arg1 errCode:(int)arg2;
@end

