//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCCanvasComponentReportBasicInfo.h"

@class WCCanvasComponentReportUrlInfo;

@interface WCCanvasComponentReportSightInfo : WCCanvasComponentReportBasicInfo
{
    unsigned int _sightDuration;
    unsigned int _playTimeInterval;
    unsigned int _playCount;
    unsigned int _playCompletedCount;
    unsigned int _clickVoiceControlCount;
    unsigned int _isAutoPlay;
    WCCanvasComponentReportUrlInfo *_thumbUrlInfo;
    WCCanvasComponentReportUrlInfo *_sightUrlInfo;
}

@property(retain, nonatomic) WCCanvasComponentReportUrlInfo *sightUrlInfo; // @synthesize sightUrlInfo=_sightUrlInfo;
@property(retain, nonatomic) WCCanvasComponentReportUrlInfo *thumbUrlInfo; // @synthesize thumbUrlInfo=_thumbUrlInfo;
@property(nonatomic) unsigned int isAutoPlay; // @synthesize isAutoPlay=_isAutoPlay;
@property(nonatomic) unsigned int clickVoiceControlCount; // @synthesize clickVoiceControlCount=_clickVoiceControlCount;
@property(nonatomic) unsigned int playCompletedCount; // @synthesize playCompletedCount=_playCompletedCount;
@property(nonatomic) unsigned int playCount; // @synthesize playCount=_playCount;
@property(nonatomic) unsigned int playTimeInterval; // @synthesize playTimeInterval=_playTimeInterval;
@property(nonatomic) unsigned int sightDuration; // @synthesize sightDuration=_sightDuration;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (id)initWithCid:(id)arg1;

@end

