//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, WCUploadTask;

@protocol WCDataUploaderDelegate <NSObject>
- (void)onDataUploadFinished:(WCUploadTask *)arg1 uploadResult:(int)arg2 uploadErrType:(int)arg3 uploadErrMsg:(NSString *)arg4;
@end

