//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WCDBConfigPerformance : NSObject
{
    _Bool m_report;
    int m_count;
}

+ (void)initialize;
@property(nonatomic) int m_count; // @synthesize m_count;
@property(nonatomic) _Bool m_report; // @synthesize m_report;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;

@end

