//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WCDeviceStepObject;

@protocol WCDeviceM7LogicDelegate <NSObject>

@optional
- (void)tryUploadStepOnObserver;
- (unsigned int)getLastHealthkitStep;
- (unsigned int)getLastM7Step;
- (void)onGotDeviceStepObject:(WCDeviceStepObject *)arg1;
@end

