//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "WCCardImageBrowserDelegate.h"

@class MMUIWindow, MMWebImageView, NSMutableArray, NSString, UIButton, UIImageView, UILabel, WCCardImageBrowserViewController, WCCardVideoViewController, WCGiftCardData;

@interface WCGiftCardLetterView : MMUIView <WCCardImageBrowserDelegate>
{
    double _maxWidth;
    double _minHeight;
    WCGiftCardData *_giftCardData;
    UILabel *_toUserLabel;
    MMWebImageView *_headImageView;
    UILabel *_fromUserLabel;
    UIImageView *_giftImageView;
    UIButton *_giftButton;
    NSMutableArray *_textLineArray;
    long long _lineCount;
    NSString *_fullImagePath;
    MMUIWindow *_fullScreenWindow;
    WCCardVideoViewController *_videoVC;
    WCCardImageBrowserViewController *_imageVC;
    NSString *_resourcePath;
    long long _downloadState;
}

@property(nonatomic) long long downloadState; // @synthesize downloadState=_downloadState;
@property(retain, nonatomic) NSString *resourcePath; // @synthesize resourcePath=_resourcePath;
@property(nonatomic) __weak WCCardImageBrowserViewController *imageVC; // @synthesize imageVC=_imageVC;
@property(nonatomic) __weak WCCardVideoViewController *videoVC; // @synthesize videoVC=_videoVC;
@property(retain, nonatomic) MMUIWindow *fullScreenWindow; // @synthesize fullScreenWindow=_fullScreenWindow;
@property(retain, nonatomic) NSString *fullImagePath; // @synthesize fullImagePath=_fullImagePath;
@property(nonatomic) long long lineCount; // @synthesize lineCount=_lineCount;
@property(retain, nonatomic) NSMutableArray *textLineArray; // @synthesize textLineArray=_textLineArray;
@property(retain, nonatomic) UIButton *giftButton; // @synthesize giftButton=_giftButton;
@property(retain, nonatomic) UIImageView *giftImageView; // @synthesize giftImageView=_giftImageView;
@property(retain, nonatomic) UILabel *fromUserLabel; // @synthesize fromUserLabel=_fromUserLabel;
@property(retain, nonatomic) MMWebImageView *headImageView; // @synthesize headImageView=_headImageView;
@property(retain, nonatomic) UILabel *toUserLabel; // @synthesize toUserLabel=_toUserLabel;
@property(retain, nonatomic) WCGiftCardData *giftCardData; // @synthesize giftCardData=_giftCardData;
@property(nonatomic) double minHeight; // @synthesize minHeight=_minHeight;
@property(nonatomic) double maxWidth; // @synthesize maxWidth=_maxWidth;
- (void).cxx_destruct;
- (void)giftButtonDidClick;
- (void)beiginDownLoad;
- (struct __CTFrame *)createFrameRefWithFramesetterRef:(struct __CTFramesetter *)arg1 fitWidth:(double)arg2 fitHeight:(double)arg3;
- (struct __CFArray *)createLinesRefWithStr:(id)arg1 width:(double)arg2;
- (void)configTextArray;
- (void)drawRect:(struct CGRect)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

