//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIView, WCDataItem, WCListBaseCellView;

@protocol WCListViewRowViewDelegate <NSObject>

@optional
- (void)onRestoreWCListCellView:(WCListBaseCellView *)arg1;
- (void)handleClickImageView:(UIView *)arg1;
- (void)handleFeedView:(WCDataItem *)arg1;
- (void)handleShortVideoView:(WCDataItem *)arg1;
- (void)handleVideoView:(WCDataItem *)arg1;
- (void)handleMusicView:(WCDataItem *)arg1;
- (void)handleTextView:(WCDataItem *)arg1;
- (UIView *)getImageViewByDataItem:(WCDataItem *)arg1;
@end

