//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCMallFunctionActivityRemarkInfo : NSObject
{
    NSString *m_nsName;
    NSString *m_nsValue;
    int m_uiShowType;
}

@property(retain, nonatomic) NSString *m_nsValue; // @synthesize m_nsValue;
@property(retain, nonatomic) NSString *m_nsName; // @synthesize m_nsName;
@property(nonatomic) int m_uiShowType; // @synthesize m_uiShowType;
- (void).cxx_destruct;

@end

