//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSString;

@protocol WCNetworkMediaInfoDelegate <NSObject>
- (void)onGotVideoUrl:(NSString *)arg1 Error:(NSError *)arg2;
@end

