//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCPayCheckPayPwdVerifyTelCodeByTokenResponse : NSObject
{
    NSString *m_nsCheckPwdTokenType;
    NSString *m_nsCheckPwdToken;
}

@property(retain, nonatomic) NSString *m_nsCheckPwdTokenType; // @synthesize m_nsCheckPwdTokenType;
@property(retain, nonatomic) NSString *m_nsCheckPwdToken; // @synthesize m_nsCheckPwdToken;
- (void).cxx_destruct;

@end

