//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WCPayOrderDetailNormalCellInfo, WCPayOrderStatusPanelButtonInfo;

@protocol WCPayOrderAndProductDetailHistoryInfoViewControllerDelegate <NSObject>
- (void)WCPayOrderAndProductDetailHistoryInfoViewControllerClickPannelButtonInfo:(WCPayOrderStatusPanelButtonInfo *)arg1;
- (void)WCPayOrderAndProductDetailHistoryInfoViewControllerClickNormalCellInfo:(WCPayOrderDetailNormalCellInfo *)arg1;
- (void)WCPayOrderAndProductDetailHistoryInfoViewControllerEvaluateOrder:(unsigned int)arg1;
- (void)WCPayOrderAndProductDetailHistoryInfoViewControllerContactBrandTel;
- (void)WCPayOrderAndProductDetailHistoryInfoViewControllerContactBrandSeller;
- (void)WCPayOrderAndProductDetailHistoryInfoViewControllerShowTranscationCell;
- (void)WCPayOrderAndProductDetailHistoryInfoViewControllerShowProductView;
- (void)WCPayOrderAndProductDetailHistoryInfoViewControllerBack;
@end

