//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, WCPayF2FReceiveDetailSummaryItem;

@interface WCPayF2FReceiveDetailResponse : NSObject
{
    long long _retCode;
    NSString *_retMsg;
    WCPayF2FReceiveDetailSummaryItem *_summaryItem;
    NSArray *_recordList;
}

@property(retain, nonatomic) NSArray *recordList; // @synthesize recordList=_recordList;
@property(retain, nonatomic) WCPayF2FReceiveDetailSummaryItem *summaryItem; // @synthesize summaryItem=_summaryItem;
@property(retain, nonatomic) NSString *retMsg; // @synthesize retMsg=_retMsg;
@property(nonatomic) long long retCode; // @synthesize retCode=_retCode;
- (void).cxx_destruct;

@end

