//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WCPayOfflinePayCodeView;

@protocol WCPayOfflinePayCodeViewDelegate <NSObject>
- (void)wcPayOfflinePayCodeViewDidCompletedSuccessAnimation:(WCPayOfflinePayCodeView *)arg1;
- (_Bool)wcPayOfflinePayCodeViewCouldStartSuccessAnimation:(WCPayOfflinePayCodeView *)arg1;
- (void)wcPayOfflinePayCodeViewAutoRefreshCountingFinished:(WCPayOfflinePayCodeView *)arg1;
- (void)wcPayOfflinePayCodeViewExitFullScreenAnimationFinished:(WCPayOfflinePayCodeView *)arg1;
@end

