//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WCPayOverseaMainWalletIdKeyReport : NSObject
{
}

+ (void)reportClickSwitchWallet;
+ (void)reportClickActionSheetItemWithOutUrl;
+ (void)reportClickActionSheetItem;
+ (void)reportClickOperation;
+ (void)reportClickGrayItemWithOutUrl;
+ (void)reportClickGrayItem;
+ (void)reportClickPayFunctionItemWithOutUrl;
+ (void)reportClickPayFunctionItem;
+ (void)reportIBGGetWalletReturnError;
+ (void)reportIBGGetWalletReturnOK;
+ (void)reportPayFunctionListReturnError;
+ (void)reportPayFunctionListReturnOK;
+ (void)reportEnterOverseaMainWallet;

@end

