//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCPayOfflinePayConfirmMessageStruct : NSObject
{
    NSString *m_nsMessageUid;
    NSString *m_nsProductName;
    NSString *m_nsProductMoney;
    NSString *m_nsProductOriginalMoney;
    unsigned long long _m_confirmType;
}

@property(nonatomic) unsigned long long m_confirmType; // @synthesize m_confirmType=_m_confirmType;
@property(retain, nonatomic) NSString *m_nsProductOriginalMoney; // @synthesize m_nsProductOriginalMoney;
@property(retain, nonatomic) NSString *m_nsProductName; // @synthesize m_nsProductName;
@property(retain, nonatomic) NSString *m_nsProductMoney; // @synthesize m_nsProductMoney;
@property(retain, nonatomic) NSString *m_nsMessageUid; // @synthesize m_nsMessageUid;
- (void).cxx_destruct;
- (void)dealloc;

@end

