//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MMTableView, MMUILabel, NSMutableArray, NSString;

@interface WCPayGPOrderHistoryViewController : WCPayBaseViewController <UITableViewDelegate, UITableViewDataSource>
{
    _Bool _bIsLoadingMore;
    _Bool _bIsDataLoadEnd;
    id <WCPayGPOrderHistoryControllerDelegate> _delegate;
    NSMutableArray *_orderHistory;
    NSString *_h5AARecordUrl;
    MMTableView *_tableView;
    MMUILabel *_tipsLabel;
}

@property(retain, nonatomic) MMUILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
@property(retain, nonatomic) MMTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool bIsDataLoadEnd; // @synthesize bIsDataLoadEnd=_bIsDataLoadEnd;
@property(nonatomic) _Bool bIsLoadingMore; // @synthesize bIsLoadingMore=_bIsLoadingMore;
@property(retain, nonatomic) NSString *h5AARecordUrl; // @synthesize h5AARecordUrl=_h5AARecordUrl;
@property(retain, nonatomic) NSMutableArray *orderHistory; // @synthesize orderHistory=_orderHistory;
@property(nonatomic) __weak id <WCPayGPOrderHistoryControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)h5RecordEnteranceBtnPress;
- (void)orderHistoryVCCancel;
- (void)genTableFooterViewAfterLoadAllData;
- (id)genTableFooterView;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)setupEmptyTipsView;
- (void)setupContentView;
- (void)setupNavigationBar;
- (void)setupData;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)refreshViewControllerWithOrderHistoryListData:(id)arg1 bIsReloadFromTop:(_Bool)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

