//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol WCPayHistoryOrderDetailViewDelegate <NSObject>
- (void)OnClickedBrandProfile:(NSString *)arg1 NickName:(NSString *)arg2;

@optional
- (void)OnClickedReceiverProfile:(NSString *)arg1;
- (void)OnClickedRetrySendMessage:(NSString *)arg1 UserName:(NSString *)arg2;
@end

