//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCPayInnerPayResponseStruct : NSObject
{
    NSString *m_nsPartnerId;
    NSString *m_nsOutTradeNumber;
}

@property(retain, nonatomic) NSString *m_nsPartnerId; // @synthesize m_nsPartnerId;
@property(retain, nonatomic) NSString *m_nsOutTradeNumber; // @synthesize m_nsOutTradeNumber;
- (void).cxx_destruct;
- (void)dealloc;

@end

