//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WCPayControlData;

@protocol WCPayOrderDetailViewControllerDelegate <NSObject>
- (void)OrderDetailBack;
- (void)OrderDetailClickCoupousInfo;
- (void)OrderDetailAddOrderCard:(WCPayControlData *)arg1;
- (void)OrderDetailAdd:(WCPayControlData *)arg1;
- (void)OrderDetailPay:(WCPayControlData *)arg1;
@end

