//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCProductAttrInfo : NSObject
{
    NSString *name;
    NSString *value;
}

@property(retain, nonatomic) NSString *value; // @synthesize value;
@property(retain, nonatomic) NSString *name; // @synthesize name;
- (void).cxx_destruct;
- (void)dealloc;

@end

