//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSMutableDictionary;

@interface WCSnsABTestFeedOperationInfo : NSObject <NSCoding>
{
    NSMutableDictionary *dicFeedIdOperationInfo;
}

@property(retain, nonatomic) NSMutableDictionary *dicFeedIdOperationInfo; // @synthesize dicFeedIdOperationInfo;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

