//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ILinkEventExt.h"
#import "ITranslateSnsMgrExt.h"
#import "RichTextLayoutDelegate.h"
#import "WXGestureDelegate.h"

@class NSString, RichTextView, UIButton, UIImageView, UIScrollView, WCDataItem, WXGesture;

@interface WCTextDetailViewController : MMUIViewController <RichTextLayoutDelegate, ILinkEventExt, WXGestureDelegate, ITranslateSnsMgrExt>
{
    UIScrollView *_bgScrollView;
    WCDataItem *_dataItem;
    NSString *_copyedText;
    RichTextView *_contentDescView;
    NSString *_contentDesc;
    WXGesture *_gesture;
    RichTextView *m_translateView;
    UIButton *m_translateStatusView;
    UIImageView *m_translateLineView;
    int eTranslateStatus;
}

+ (id)makeDataWrapForWCTranslate:(id)arg1;
- (void).cxx_destruct;
- (void)onTranslateSnsChanged:(id)arg1;
- (void)onTranslateSnsFailed:(id)arg1 errTip:(id)arg2;
- (double)initTranslateStatusButton:(_Bool)arg1 withTitle:(id)arg2;
- (double)initContentTranslateView:(id)arg1 andSuperScrollView:(id)arg2;
- (void)onTranslate:(id)arg1;
- (id)GetTranslateSnsKeyID;
- (void)gestureWillEndTransition:(id)arg1 isCanceld:(_Bool)arg2;
- (void)onTextLongPressed:(id)arg1 withRect:(struct CGRect)arg2 withView:(id)arg3;
- (void)onPhoneLongPressed:(id)arg1 withRect:(struct CGRect)arg2 withView:(id)arg3;
- (void)onLinkLongPressed:(id)arg1 withRect:(struct CGRect)arg2 withView:(id)arg3;
- (void)showMenuItemForText:(id)arg1 withRect:(struct CGRect)arg2 isWord:(_Bool)arg3 withView:(id)arg4;
- (void)onExpose:(id)arg1;
- (void)onFavAddForTranslated:(id)arg1;
- (void)onFavAdd:(id)arg1;
- (void)onCopy:(id)arg1;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (_Bool)canBecomeFirstResponder;
- (void)initGestureRecognizer;
- (void)viewDidLayoutSubviews;
- (void)reloadView;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithDataItem:(id)arg1;
- (void)onMenuControllerWillHide:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

