//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class WCDataItem, WCSnsABTestTipData;

@interface WCTimelineCellABTestBaseTip : MMUIView
{
    WCSnsABTestTipData *tipData;
    WCDataItem *dataItem;
}

+ (double)heightForTipView:(id)arg1;
@property(readonly, nonatomic) WCDataItem *dataItem; // @synthesize dataItem;
@property(readonly, nonatomic) WCSnsABTestTipData *tipData; // @synthesize tipData;
- (void).cxx_destruct;
- (void)resetStatus;
- (void)resetView:(id)arg1;
- (void)initView;
- (id)initWithTipData:(id)arg1 dataItem:(id)arg2 frame:(struct CGRect)arg3;
- (id)initWithTipData:(id)arg1 dataItem:(id)arg2;

@end

