//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCTimelineCellABTestBaseTip.h"

@interface WCTimelineCellABTestBannerTip : WCTimelineCellABTestBaseTip
{
}

+ (double)heightForTipView:(id)arg1;
- (void)onActionJump:(id)arg1;
- (void)initView;

@end

