//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWebView.h"

@class NSString;

@interface WebSearchView : UIWebView
{
    _Bool _bUseForSuggestion;
    unsigned long long _bizType;
    NSString *_keyword;
}

@property(retain, nonatomic) NSString *keyword; // @synthesize keyword=_keyword;
@property(nonatomic) unsigned long long bizType; // @synthesize bizType=_bizType;
@property(nonatomic) _Bool bUseForSuggestion; // @synthesize bUseForSuggestion=_bUseForSuggestion;
- (void).cxx_destruct;

@end

