//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "MMImageLoaderObserver.h"

@class NSString, NSURL;

@interface WebSearchImageTask : MMObject <MMImageLoaderObserver>
{
    NSURL *_url;
    id <WebSearchImageTaskDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)ImageDidFail:(id)arg1;
- (void)ImageDidLoadWithData:(id)arg1 Url:(id)arg2;
- (void)asynDownloadImage;
- (void)dealloc;
- (id)initWithUrl:(id)arg1 andDelegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

