//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WeChatOutGiftCard : NSObject
{
    NSString *_price;
    NSString *_dateWording;
    NSString *_fromUserName;
    NSString *_headImgUrl;
    NSString *_expiredWording;
}

@property(retain, nonatomic) NSString *expiredWording; // @synthesize expiredWording=_expiredWording;
@property(retain, nonatomic) NSString *headImgUrl; // @synthesize headImgUrl=_headImgUrl;
@property(retain, nonatomic) NSString *fromUserName; // @synthesize fromUserName=_fromUserName;
@property(retain, nonatomic) NSString *dateWording; // @synthesize dateWording=_dateWording;
@property(retain, nonatomic) NSString *price; // @synthesize price=_price;
- (void).cxx_destruct;

@end

