//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WNNoteItemUtilBase.h"

@interface WNNoteFileItemUtil : WNNoteItemUtilBase
{
}

- (void)insertItem:(id)arg1 isUpdate:(_Bool)arg2 isConfigData:(_Bool)arg3;
- (void)onClickItem:(id)arg1;
- (void)onAddItemBegin:(id)arg1;
- (void)dealloc;
- (id)init;

@end

