//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface WxaAppRecord : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *appid; // @dynamic appid;
@property(nonatomic) int appstate; // @dynamic appstate;
@property(nonatomic) int enterScene; // @dynamic enterScene;
@property(retain, nonatomic) NSString *ext; // @dynamic ext;
@property(nonatomic) unsigned int key; // @dynamic key;
@property(retain, nonatomic) NSString *networkType; // @dynamic networkType;
@property(retain, nonatomic) NSString *nsId; // @dynamic nsId;
@property(retain, nonatomic) NSString *sceneNote; // @dynamic sceneNote;
@property(retain, nonatomic) NSString *sessionId; // @dynamic sessionId;
@property(nonatomic) unsigned int time; // @dynamic time;
@property(nonatomic) unsigned int type; // @dynamic type;
@property(nonatomic) int usedState; // @dynamic usedState;
@property(nonatomic) unsigned int value; // @dynamic value;

@end

