//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WCDataBase;

@interface WXGBackupIndexDB : NSObject
{
    WCDataBase *m_db;
}

- (void).cxx_destruct;
- (_Bool)runTransaction:(CDUnknownBlockType)arg1 stateDidChanged:(CDUnknownBlockType)arg2;
- (_Bool)runTransaction:(CDUnknownBlockType)arg1;
- (id)p_getRecoverInfoTable;
- (id)p_getMsgListTable;
- (id)getAllSessionName;
- (unsigned long long)getTotalSessionCount;
- (id)getRecoverInfoObjectOfSession:(id)arg1;
- (_Bool)deleteIndexObjectByMsgID:(id)arg1;
- (id)getMsgListIDForSessionName:(id)arg1;
- (id)getMsgListIDArray;
- (long long)getLastTimeOfSessionName:(id)arg1;
- (void)insertDataWithRecoverInfoObject:(id)arg1;
- (void)insertDataWithIndexObject:(id)arg1;
- (void)removeDBFile;
- (void)closeDB;
- (void)createDataBase;
- (void)dealloc;
- (id)init;

@end

